(function ($) {
    var basepath = 'http://ja1.gamersky.com/';
    var tgList = [
        //首页
        {
            tid:'#top_index_660',
            url:basepath+'banner/top_index_660.js'
        },
        {
            tid:'#back_index1100_all',
            url:basepath+'background/back_index1100_all.js'
        },
        {
            tid:'#index_fugai_900',
            //url:basepath+'fugai/index_fugai_900.js'
        },
        {
            tid:'#index_siye',
            url:basepath+'common/index_siye.js'
        },
        {
            tid:'#index_tips',
            url:basepath+'tips/index_tips.js'
        },
        {
            tid:'#index_new_tips',
            url:basepath+'tips/index_new_tips.js'
        },
        {
            tid:'#index_left_ad',
            url:basepath+'common/index_left_ad.js'
        },
        {
            tid:'#index_xiaya',
            url:basepath+'fugai/index_xiaya.js'
        },
        {
            tid:'#index_xiaya_swf',
            url:basepath+'background/index_xiaya_swf.js'
        },
        {
            tid:'#adscontainer_banner_new_top_index_1060_1',
            url:basepath+'banner/new_top_index_1060_1.js'
        },
        {
            tid:'#adscontainer_banner_new_top_index_1060_2',
            url:basepath+'banner/new_top_index_1060_2.js'
        },
        {
            tid:'#adscontainer_banner_new_top_index_1060_3',
            //url:basepath+'banner/new_top_index_1060_3.js'
        },
        {
            tid:'#common_huandeng',
            url:basepath+'common/huandeng.js'
        },
        {
            tid:'#adscontainer_www_index_feturegame',
            url:basepath+'www/index_feturegame.js'
        },
        {
            tid:'#common_qtz',
            url:basepath+'common/qtz.js'
        },
        {
            tid:'#adscontainer_banner_new_second_index_1060',
            url:basepath+'banner/new_second_index_1060.js'
        },
        {
            tid:'#adscontainer_banner_new_middle_index_1060_1',
            url:basepath+'banner/new_middle_index_1060_1.js'
        },
        {
            tid:'#adscontainer_banner_new_middle_index_1060_2',
            url:basepath+'banner/new_middle_index_1060_2.js'
        },
        {
            tid:'#adscontainer_banner_new_middle_index_1060_3',
            url:basepath+'banner/new_middle_index_1060_3.js'
        },
        {
            tid:'#adscontainer_banner_new_middle_index_1060_4',
            url:basepath+'banner/new_middle_index_1060_4.js'
        },
        {
            tid:'#adscontainer_banner_new_middle_index_1060_5',
            url:basepath+'banner/new_middle_index_1060_5.js'
        },
        {
            tid:'#adscontainer_banner_new_bottom_index_1060',
            url:basepath+'banner/new_bottom_index_1060.js'
        },
        //新——全站通栏1
        {
            tid:'#new_top_allsite_970_1',
            url:basepath+'banner/new_top_allsite_970_1.js'
        },
        //新——全站通栏2
        {
            tid:'#new_top_allsite_970_2',
            url:basepath+'banner/new_top_allsite_970_2.js'
        },
        //新——全站通栏3
        {
            tid:'#new_top_allsite_970_3',
            url:basepath+'banner/new_top_allsite_970_3.js'
        },
        //全站通栏1
        {
            tid:'#top_allsite_950_1',
            url:basepath+'banner/top_allsite_950_1.js'
        },
        //全站通栏2
        {
            tid:'#top_allsite_950_2',
            url:basepath+'banner/top_allsite_950_2.js'
        },
        //全站通栏3
        {
            tid:'#top_allsite_950_3',
            url:basepath+'banner/top_allsite_950_3.js'
        },
        //全站顶部横幅
        {
            tid:'#top_allsite_660',
            url:basepath+'banner/top_allsite_660.js'
        },
        //动漫全站顶部通栏
        {
            tid:'#top_allsite_acg_660',
            url:basepath+'banner/top_allsite_acg_660.js'
        },
        //动漫内页一屏通栏
        {
            tid:'#new_top_allsite_acg_970_1',
            url:basepath+'banner/new_top_allsite_acg_970_1.js'
        },
        //新——频道通栏1
        {
            tid:'#top_pd_1060_1',
            url:basepath+'banner/top_pd_1060_1.js'
        },
        //steam专区首页一屏通栏1
        {
            tid:'#steam_1000_1',
            url:basepath+'banner/steam_1000_1.js'
        },
        //专区通栏--暗黑3
        {
            tid:'#zq_970_n_ah3',
            url:basepath+'common/zq_970_n_ah3.js'
        },
        //内容页分页Banner
        {
            tid:'#new_page_allsite_620',
            url:basepath+'banner/new_page_allsite_620.js'
        },
        //硬件频道通栏1
        {
            tid:'#hardware_top_950_1',
            url:basepath+'banner/hardware_top_950_1.js'
        },
        //下载诱导v2
        {
            tid:'#common_down_info',
            url:basepath+'common/down_info.js'
        },
        //下载频道内容页中部横幅
        {
            tid:'#banner_down_link',
            url:basepath+'banner/down_link.js'
        },
        //新——PC频道首页覆盖
        {
            tid:'#pc_fugai_900',
            url:basepath+'fugai/pc_fugai_900.js'
        },
        //硬件频道右侧方块1
        {
            tid:'#T300_hardware',
            url:basepath+'www/T300_hardware.js'
        },
        //动漫内容页背景
        {
            tid:'#tgs_back_acg460',
            url:basepath+'background/back_acg460.js'
        },
        //下载内容页背景（含攻略）-新
        {
            tid:'#tgs_back_down1000',
            url:basepath+'background/back_down1000.js'
        },
        //下载频道首页背景
        {
            tid:'#tgs_back_index1100_down',
            url:basepath+'background/back_index1100.down.js'
        },
        //频道首页背景
        {
            tid:'#tgs_back_index1100',
            url:basepath+'background/back_index1100.js'
        },
        //PC频道首页背景
        {
            tid:'#tgs_back_index1100_pc',
            url:basepath+'background/back_index1100.pc.js'
        },
        //专区频道首页背景
        {
            tid:'#tgs_back_index1100_zq',
            url:basepath+'background/back_index1100.zq.js'
        },
        //列表页背景（与专区页背景一致）
        {
            tid:'#tgs_back_list1100',
            url:basepath+'background/back_list1100.js'
        },
        //新闻频道内容页背景
        {
            tid:'#tgs_back_news960',
            url:basepath+'background/back_news960.js'
        },
        //新闻频道内容页背景-新
        {
            tid:'#tgs_back_news1000',
            url:basepath+'background/back_news1000.js'
        },
        //文库娱乐内容页背景
        {
            tid:'#tgs_back_zatan1000',
            url:basepath+'background/back_zatan1000.js'
        },
        //专区页背景V4
        {
            tid:'#tgs_back_zq1000',
            url:basepath+'background/back_zq1000.js'
        },
        //专区页背景(三国志)V4
        {
            tid:'#tgs_back_zq1000_sg',
            url:basepath+'background/back_zq1000_sg.js'
        },
        //专区通栏1
        {
            tid:'#gsincome_zq_zq_950_n',
            url:basepath+'common/zq_950_n.js'
        },
        //专区通栏2
        {
            tid:'#gsincome_zq_600',
            url:basepath+'common/zq_600.js'
        },
        //专区右侧方块2
        {
            tid:'#gsincome_zq_right_300_2',
            url:basepath+'common/zq_right_300_2.js'
        },
        //专区页背景
        {
            tid:'#background_back_zq950',
            url:basepath+'background/back_zq950.js'
        },
        //新——专区页覆盖
        {
            tid:'#fugai_zq_fugai_900',
            url:basepath+'fugai/zq_fugai_900.js'
        },
        //新——专区通栏1
        {
            tid:'#gsincome_zq_970_n',
            url:basepath+'common/zq_970_n.js'
        },
        //新——专区通栏2
        {
            tid:'#gsincome_zq_600_new',
            url:basepath+'common/zq_600_new.js'
        },
        //专区页背景-自动
        {
            tid:'#background_back_zq_auto',
            url:basepath+'background/back_zq_auto.js'
        },
        //S专区通栏1
        {
            tid:'#gsincome_szq_1160',
            url:basepath+'common/szq_1160.js'
        },
        //S专区通栏2
        {
            tid:'#gsincome_szq_835',
            url:basepath+'common/szq_835.js'
        },
        //首页 异性擎天柱
        {
            tid:'#index_qtz_yixing',
            //url:'ja/'+'index/qtz_yixing.js'
        },
        //首页 一屏通栏3 变形
        {
            tid:'#index_fudong_bot',
            url:'ja/index/new_top_index_1060_3_big.js'
        }
    ];
    function loadGsTgJs(tid,url) {
        if($(tid).length>0){
            $.getScript(url);
        }
    }
    function loadList() {
        for(var i = 0;i<tgList.length;i++){
            loadGsTgJs(tgList[i].tid,tgList[i].url);
        }
    }
    $(function () {
        $.ajax({
            dataType:'Script',
            url:'ja/gs.common.income.js',
            cache:false,
            success:function () {
                loadList();
            }
        });
    });
})(jQuery);