var z358Data = {
    dto:{
        //开放世界
        kfsj:[
            {kid:'0',name:'马匹',
                list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_5/001.jpg',txt:'玩家从初期便可以骑乘马匹，从街道与村庄的马屋能购买到优秀的马匹。已购入的马匹，可以利用马屋内的厩舍随时变更。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_5/002.jpg',txt:'游戏内可以骑乘各式各种毛色的马匹。当然也包含那有名的赤兔马。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_5/003.jpg',txt:'马匹可以行走长远距离，在骑乘时击破敌人，让马匹成长。找到自己喜爱的马匹后，请好好培养它。'}
                ]
            },
            {kid:'1',name:'探索·采取',list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_6/001.jpg',txt:'城市旁的树丛，建造有高人一等的观景台。能得知周边状况，找到后请务必前往，仔细观察周边情况。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_6/002.jpg',txt:'从观景台观看周遭环境，能实时获得广大范围的周边情报，不管是对进行任务或是探索上都十分有利'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_6/003.jpg',txt:'郊外的森林地带、溪流等处，存在素材的“群生地”。可从此处获得稀少素材，为了有效率地开发武器与道具，请经常检查地图上的群生地。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_6/004.jpg',txt:'设置陷阱箱后，经过一定时间可以获得道具等物。陷阱箱有大・中・小３种尺寸，越大的陷阱箱可获得越珍贵的道具。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_6/005.jpg',txt:'在城市内的河流进行垂钓，可以获得素材及古钱。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_6/006.jpg',txt:'能狩猎狼、熊等野生动物。开发对野生动物特效的箭能精进狩猎之道。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_6/007.jpg',txt:'进行狩猎，可以获得狩猎点数。依入手的狩猎点数，可从好事者处换取古钱与宝玉等报酬。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_6/008.jpg',txt:'要开发武器与道具等，需要收集记载所需素材的竹简，完成物品制作。竹简可于任务达成时获得之外，也可从打倒的敌人身上获得。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_6/009.jpg',txt:'持有竹简上所记载的素材，便可以开发新道具与武器。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_6/010.jpg',txt:'上级武器也只要收集竹简上记载的素材，便可以进行开发。'}
                ]
            },
            {kid:'2',name:'常服',list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_11/001.jpg',txt:'本作加入全新的武将常服形象，不打仗的时候武将穿的自然和战时不一样，而在城镇之中探索时还能偶遇到穿着常服的武将。'}
                ]
            },
            {kid:'3',name:'城镇村落',list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_7/001.jpg',txt:'存在可购入马匹的马屋。为了能更有效率在宽阔的地图上移动，希望能取得具备高能力的名驹。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_7/002.jpg',txt:'古钱搜集家处，可以利用取得的古钱购买珍贵的道具。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_7/003.jpg',txt:'在锻冶屋处，可以买卖武器等之外，也可以消耗素材，制作武器或道具。必要的素材，写在任务报酬等可取得的竹简上。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_7/004.jpg',txt:'料理店可以购入提升经验值、攻击力与跳跃力等武将能力，暂时使游戏进行上更为有利的美味料理。 调理时所需的必要材料，可以在料理店进行确认。'}
                ]
            },
            {kid:'4',name:'秘密基地',list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_8/001.jpg',txt:'幅员辽阔的地图上，在许多场所存在着可设定为玩家武将秘密基地之用的空屋，各空屋可以一定金额购买。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_8/002.jpg',txt:'位于大都市洛阳徒步圈内，立地良好的优良对象。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_8/003.jpg',txt:'位于中国首屈一指的绝美景点九寨沟‧黄龙附近的人气物件。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_8/004.jpg',txt:'于中国五岳之一华山之顶，可一望美丽山麓景观的景观物件。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_8/005.jpg',txt:'购买秘密基地后，能发送请帖给有交流关系的无双武将。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_8/006.jpg',txt:'受邀请的无双武将来访。穿着不同平常的日常服装来访。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_8/007.jpg',txt:'秘密基地能照自己的喜好摆设家具。摆设家具能发挥各式各样的效果，增加玩家在秘密基地能做的事。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_8/008.jpg',txt:'像是能做料理的炉灶、能开发道具的炼成鼎或能恢复体力的寝具等，能构筑成一个有利于游戏进行的环境。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_8/009.jpg',txt:'另外，还有着可以更换服装穿着的衣柜或是能设定秘密基地中播放的背景音乐用的铜锣等等，能够配置各式各样的家具或装饰品，将房间布置成自己喜好的风格。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_8/010.jpg',txt:'家具能从街道或村落的古钱收藏家或贸易商的店内购入。'}
                ]
            },
            {kid:'5',name:'钓鱼',list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_11/002.jpg',txt:'在河边垂钓，可以获得食材等素材。'}
                ]
            },
            {kid:'6',name:'遭遇强敌',list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_9/001.jpg',txt:'在地图上移动时，有可能会遇到不畏惧玩家攻击的强力盗贼。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_9/002.jpg',txt:'击倒强敌后，有机会得到不常见的高价道具。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_9/003.jpg',txt:'全身黑毛的狼，与比平常还凶暴的野兽对峙时，走为上策也是个良策吧。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_9/004.jpg',txt:'泛出稀有蓝光毛色的老虎，若因这神秘姿态看傻了眼而松懈的话，可是有丧命的危险。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_9/005.jpg',txt:'白毛的熊，被那强力的一巴掌打中，可免不了受到极大的伤害。'}
                ]
            },
            {kid:'7',name:'观景',list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_10/001.jpg',txt:'黄河'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_10/002.jpg',txt:'建宁'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_10/003.jpg',txt:'洛阳'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_10/004.jpg',txt:'沙漠'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_10/005.jpg',txt:'嵩山'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_10/006.jpg',txt:'新野'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_10/007.jpg',txt:'雨林'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_10/008.jpg',txt:'长城'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_10/009.jpg',txt:'竹林'}
                ]
            },
            {kid:'8',name:'路标',list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_11/004.jpg',txt:'找不到路了怎么办？路标会显示周围景点等信息。'}
                ]
            },
            {kid:'9',name:'救援村民',list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180201_zq_281_11/003.jpg',txt:'在路途中，可以帮助村民击败来敌。'}
                ]
            }
        ],
        //武将介绍
        heros:{
            wei:{
                nav:'魏',
                list:[
                    {
                        name:{
                            f:'曹操',
                            l:'孟德',
                            s:'苍紫霸道'
                        },
                        cv:'岸野幸正',
                        vu:'XMzM4MDU4OTE0MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/曹操.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/曹操1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/曹操2.jpg'
                        },
                        des:'<p>之后的魏王。人称“乱世奸雄”。</p><p>长于判断与决断。参加黄巾讨伐军后展现头角。慢慢于中原巩固地盘，建立起魏的基础。</p><p>是名野心家与合理主义者，时而面对他人严苛，使周遭人陷入恐怖之中。</p><p>著有兵书，喜好吟诗，为文武兼通之才。</p>'
                    },
                    {
                        name:{
                            f:'蔡文姬',
                            l:'',
                            s:'忧愁的才女'
                        },
                        cv:'吉川未来',
                        vu:'XMzM4MDU4ODE0OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/蔡文姬.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/蔡文姬1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/蔡文姬2.jpg'
                        },
                        des:'<p>东汉议郎蔡邕之女。</p><p>作为才女的评价颇高，同时也是通晓音律的深闺美人。</p><p>乱世当中不幸被游牧民族匈奴所掳走，后由怜悯其遭遇的曹操救出。</p><p>文静且虚幻的态度下，暗藏着聪慧及坚强的气度。</p>'
                    },
                    {
                        name:{
                            f:'曹丕',
                            l:'子桓',
                            s:'伶俐的次代继承人'
                        },
                        cv:'神奈延年',
                        vu:'XMzM4MDU4OTc1Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/曹丕.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/曹丕1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/曹丕2.jpg'
                        },
                        des:'<p>曹操之子，天生背负着继承霸业之命运。</p><p>具备统领次世代之才气，但受环境与理智影响，有时对他人发言冷酷或轻视他人。</p><p>冷静看待万事，能从容处理一切事务。</p>'
                    },
                    {
                        name:{
                            f:'曹仁',
                            l:'子孝',
                            s:'沈著的盾'
                        },
                        cv:'江川央生',
                        vu:'XMzM4MDU5MDM1Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/曹仁.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/曹仁1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/曹仁2.jpg'
                        },
                        des:'<p>曹操的堂兄弟。与夏侯惇、夏侯渊们同样，自曹操起兵时便投入其下，置身乱世当中。</p><p>是位大胆且精通百般武艺的武将，也深受曹操信赖。</p><p>是个有礼貌温和的人物，不好争斗，祈求终结乱世而勇赴战场。</p>'
                    },
                    {
                        name:{
                            f:'曹休',
                            l:'文烈',
                            s:'驯良之骏马'
                        },
                        cv:'佐藤拓也',
                        vu:'XMzM4MDU5MDkyNA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/曹休.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/曹休1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/曹休2.jpg'
                        },
                        des:'<p>曹操的族子，于曹操举兵之际远从吴郡归返，因此获曹操称赞“此吾家千里驹也”。</p><p>亦因早年丧父，曹操将之视如己出。</p>'
                    },
                    {
                        name:{
                            f:'典韦',
                            l:'',
                            s:'勇猛的忠义'
                        },
                        cv:'中井和哉',
                        vu:'XMzM4MDU5MTQxMg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/典韦.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/典韦1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/典韦2.jpg'
                        },
                        des:'<p>因身怀怪力与魁伟风貌，被曹操授予古代豪杰“恶来”之名。</p><p>与粗暴的言行粗旷的外观迥异，比他人更重忠节。担任曹操护卫相当活跃。</p>'
                    },
                    {
                        name:{
                            f:'郭嘉',
                            l:'奉孝',
                            s:'享乐的才子'
                        },
                        cv:'神原大地',
                        vu:'XMzM4MDU5MjAxMg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/郭嘉.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/郭嘉1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/郭嘉2.jpg'
                        },
                        des:'<p>曹操麾下军师。</p><p>依靠优越的洞察力多次献策多次获胜，受到曹操的高度评价。</p><p>温和待人，笑容不绝。</p>'
                    },
                    {
                        name:{
                            f:'贾诩',
                            l:'文和',
                            s:'洞悉先机的男子'
                        },
                        cv:'石川英郎',
                        vu:'XMzM4MDU5MjUxMg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/贾诩.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/贾诩1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/贾诩2.jpg'
                        },
                        des:'<p>飘然生活于乱世的策略家。</p><p>仕官于张绣后，成功击退曹操，之后由于其策略长才受曹操重用。</p><p>擅长算计献策，但不阐述自己的理想。</p>'
                    },
                    {
                        name:{
                            f:'乐进',
                            l:'文谦',
                            s:'恐怖至极的先锋队长'
                        },
                        cv:'伊藤健太郎',
                        vu:'XMzM4MDU5MzE0MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/乐进.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/乐进1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/乐进2.jpg'
                        },
                        des:'<p>出身曹操麾下文官的武将。</p><p>自曹操崛起时便投身前锋，于诸多战役中冲阵陷阵。</p><p>个子不高且文静，但身体能力不错。</p>'
                    },
                    {
                        name:{
                            f:'李典',
                            l:'曼成',
                            s:'第六感精准的男人'
                        },
                        cv:'鸟海浩辅',
                        vu:'XMzM4MDU5MzY1Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/李典.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/李典1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/李典2.jpg'
                        },
                        des:'<p>曹操崛起时便投身麾下的历战勇士。</p><p>看似轻率的态度，常令周围的人大吃一惊。</p><p>第六感十分精准，总是能及早识破敌人陷阱与计谋。</p>'
                    },
                    {
                        name:{
                            f:'满宠',
                            l:'伯宁',
                            s:'微笑之策士'
                        },
                        cv:'青木崇',
                        vu:'XMzM4MDU5NDI1Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/满宠.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/满宠1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/满宠2.jpg'
                        },
                        des:'<p>魏国智将。在许多防卫战中巧妙运用计略以及陷阱，贡献良多。</p><p>口才亦佳，曾劝旧识徐晃出仕曹操。</p>'
                    },
                    {
                        name:{
                            f:'庞德',
                            l:'令明',
                            s:'无所动摇的士魂'
                        },
                        cv:'森田成一',
                        vu:'XMzM4MDU5NDgyNA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/庞德.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/庞德1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/庞德2.jpg'
                        },
                        des:'<p>原为西凉马腾、马超手下，曹操攻入汉中时投靠曹操。</p><p>行事冷静，意志坚定，只要下定决心开始行动便会无所动摇。</p>'
                    },
                    {
                        name:{
                            f:'王异',
                            l:'',
                            s:'为复仇绽放的妖花'
                        },
                        cv:'桑岛法子',
                        vu:'XMzM4MDU5NTQwNA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/王异.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/王异1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/王异2.jpg'
                        },
                        des:'<p>汉中豪族王氏之女。</p><p>由于一族被西凉军阀所灭，立誓对马超复仇，成为魏国参谋。</p><p>不会与他人有过于亲密的关系，但是……</p>'
                    },
                    {
                        name:{
                            f:'夏侯惇',
                            l:'元让',
                            s:'单眼将星'
                        },
                        cv:'中井和哉',
                        vu:'XMzM4MDU5NjAxMg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/夏侯惇.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/夏侯惇1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/夏侯惇2.jpg'
                        },
                        des:'<p>武勇皆优的独眼将军。为主君曹操的从兄弟。</p><p>是名冷静沉着的将领，作为一介武人，有着一流的武艺。</p><p>为回应曹操的信赖，为支持其霸业，投身于战场之上。</p>'
                    },
                    {
                        name:{
                            f:'夏侯渊',
                            l:'妙才',
                            s:'爽朗的斗将'
                        },
                        cv:'德山靖彦',
                        vu:'XMzM4MDU5NjU3Ng',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/夏侯渊.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/夏侯渊1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/夏侯渊2.jpg'
                        },
                        des:'<p>为夏侯惇从兄弟，与夏侯惇一起，自曹操举兵时便追随其下，负责部队之一翼。</p><p>擅长突击，武艺上亦长于弓箭。</p><p>温柔以待同伴，对敌人严厉，为表里分明的人物。</p>'
                    },
                    {
                        name:{
                            f:'徐晃',
                            l:'公明',
                            s:'廉直的武将'
                        },
                        cv:'山本圭一郎',
                        vu:'XMzM4MDU5NzEzNg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/徐晃.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/徐晃1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/徐晃2.jpg'
                        },
                        des:'<p>智勇双全的武将，曹操赞他“将军之功，逾孙武”。</p><p>欲穷极武艺，具备求道者专注的气质。</p><p>对于具备高武艺及德行的人物，即使是敌人，也会表示敬意。</p>'
                    },
                    {
                        name:{
                            f:'许褚',
                            l:'仲康',
                            s:'纯真的武士'
                        },
                        cv:'吉水孝宏',
                        vu:'XMzM4MDU5NzU1Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/许褚.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/许褚1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/许褚2.jpg'
                        },
                        des:'<p>是个大块头，担任曹操近身护卫。</p><p>个性不似武士，十分悠哉。 大方的行事风格与天真无邪的言行，总是能缓和四周气氛。</p><p>另一方面在战场上冲锋陷阵时，有如老虎般勇猛，因而获得“虎痴”的绰号。</p>'
                    },
                    {
                        name:{
                            f:'荀攸',
                            l:'公达',
                            s:'泰然自若之战术家'
                        },
                        cv:'滨田贤二',
                        vu:'XMzM4MDU5ODA1Ng',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/荀攸.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/荀攸1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/荀攸2.jpg'
                        },
                        des:'<p>仕于曹操麾下的军事家。于许多大战役、局部战役出谋献策，为曹操军夺得胜利。</p><p>与荀彧为亲戚关系（荀彧祖父与荀攸曾祖父为兄弟）。</p>'
                    },
                    {
                        name:{
                            f:'荀彧',
                            l:'文若',
                            s:'灿烂的王佐之才'
                        },
                        cv:'大原崇',
                        vu:'XMzM4MDU5ODY0NA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/荀彧.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/荀彧1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/荀彧2.jpg'
                        },
                        des:'<p>支撑起曹操霸业的名军师。</p><p>提出许多建言与谋略，年纪轻轻就被誉为“王佐之才”。</p><p>除此之外，还利用与生俱来的慧眼与广阔的人脉为武器，发掘有才能之人。</p>'
                    },
                    {
                        name:{
                            f:'于禁',
                            l:'文则',
                            s:'严峻的常胜将军'
                        },
                        cv:'宫内敦士',
                        vu:'XMzM4MDU5OTEwOA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/于禁.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/于禁1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/于禁2.jpg'
                        },
                        des:'<p>曹操手下，靠自身实力脱颖而出的将领。</p><p>多次战斗中展现功绩，因而威名远播。</p><p>非常注重军规，古板不近人情的性格成为无论敌我方都惧怕的对象。</p>'
                    },
                    {
                        name:{
                            f:'张辽',
                            l:'文远',
                            s:'无与伦比的利刃'
                        },
                        cv:'田中大文',
                        vu:'XMzM4MDYwMTE0OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/张辽.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/张辽1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/张辽2.jpg'
                        },
                        des:'<p>原为吕布麾下将领，不断转战各地。自吕布败死后，投身曹操。</p><p>个性冷静沉着，能做出正确判断，掌握整个战场情势。为魏五子良将之首。</p><p>重义气，对敌人也不失礼。</p>'
                    },
                    {
                        name:{
                            f:'张郃',
                            l:'儁乂',
                            s:'灿烂的斗士'
                        },
                        cv:'幸野善之',
                        vu:'XMzM4MDYwMTk1Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/张郃.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/张郃1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/张郃2.jpg'
                        },
                        des:'<p>五子良将之一，具备绅士般的气度以及诱人的魅力。</p><p>不只擅长武艺，也喜好读书和音乐。</p>'
                    },
                    {
                        name:{
                            f:'甄姬',
                            l:'',
                            s:'雅丽之花'
                        },
                        cv:'住友优子',
                        vu:'XMzM4MDYwMjY2MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_3/甄姬.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/甄姬1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_4/甄姬2.jpg'
                        },
                        des:'<p>倾国美女。人赞其肌肤若玉，貌美如花。</p><p>原本为袁绍次男袁熙之妻，但于曹操攻陷冀州时，儿子曹丕对其一见倾心，遂强娶为妻。</p><p>有着喜爱歌曲与音乐的优雅嗜好，具备不谄媚他人的凛然之美与高风亮节的高贵节操。</p>'
                    }
                ]
            },
            shu:{
                nav:'蜀',
                list:[
                    {
                        name:{
                            f:'鲍三娘',
                            l:'',
                            s:'天真的元气少女'
                        },
                        cv:'野中蓝',
                        vu:'XMzM4MDQ5MzM2OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/鲍三娘.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/鲍三娘1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/鲍三娘2.jpg'
                        },
                        des:'<p>鲍家三女，对战场上遇到的关索抱有好感，便随他四处闯荡。</p><p>勇敢向前，个性开朗。</p>'
                    },
                    {
                        name:{
                            f:'法正',
                            l:'孝直',
                            s:'全盘回报的剧毒'
                        },
                        cv:'桥诘知久',
                        vu:'XMzM4MDQ5MzcwMA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/法正.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/法正1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/法正2.jpg'
                        },
                        des:'<p>达成刘备入蜀大业的功臣。原是刘璋的下属。</p> <p>擅长策画谋略，作为参谋成功平定益州，汉中攻略时也可见他积极的身影。</p> <p>但为人睚眦必报。</p>'
                    },
                    {
                        name:{
                            f:'关平',
                            l:'',
                            s:'次代的武士'
                        },
                        cv:'中尾良平',
                        vu:'XMzM4MDQ5NDE2OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/关平.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/关平1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/关平2.jpg'
                        },
                        des:'<p>原为河北关定次子。</p><p>当刘备与结拜兄弟会合时，留宿关定家，被关羽收为义子。</p><p>个性纯粹耿直，因一条筋的个性与对关羽的憧憬，参加刘备军队后，在短时间内便提高了自己的武艺境界。</p>'
                    },
                    {
                        name:{
                            f:'关索',
                            l:'',
                            s:'纯真的美男子'
                        },
                        cv:'三浦祥朗',
                        vu:'XMzM4MDQ5NDQ1Ng',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/关索.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/关索1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/关索2.jpg'
                        },
                        des:'<p>关羽之子。认真一根筋的个性，在做任何事都加倍努力，真诚待人。</p><p>博得“花关索”美名，在民间人气甚高。</p><p>无意中，常吸引不少女性的目光。</p>'
                    },
                    {
                        name:{
                            f:'关兴',
                            l:'安国',
                            s:'爽朗的军神后继者'
                        },
                        cv:'岛崎信长',
                        vu:'XMzM4MDQ5NDY0NA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/关兴.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/关兴1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/关兴2.jpg'
                        },
                        des:'<p>关羽之子。幼时便博得周遭好评，诸葛亮也相当期待其发展。</p><p>不多话，常独自思考，处事精明的天才。</p><p>年轻但武艺高强，北伐时与张苞一同活跃于战场。</p>'
                    },
                    {
                        name:{
                            f:'关银屏',
                            l:'',
                            s:'无自觉的怪力美少女'
                        },
                        cv:'三上枝织',
                        vu:'XMzM4MDQ5NTEwMA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/关银屏.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/关银屏1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/关银屏2.jpg'
                        },
                        des:'<p>关羽之女，关平、关兴、关索的妹妹。</p><p>有着过人的美貌，以学习护身术的心情学习武艺，却意外地高强。</p><p>天生怪力，但本人从未注意到这点。</p>'
                    },
                    {
                        name:{
                            f:'关羽',
                            l:'云长',
                            s:'军神，刀刃上是义气'
                        },
                        cv:'増谷康纪',
                        vu:'XMzM4MDQ5NTU0OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/关羽.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/关羽1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/关羽2.jpg'
                        },
                        des:'<p>蜀国五虎将之首。为人重义气，武艺高强。是少见的英雄。</p><p>与刘备、张飞结拜，对蜀国的建国贡献极大。</p><p>有着美丽长须人赞“美髯公”，此名后成为其通称。</p><p>与义兄有着迥异的魅力，不分敌我皆十分认同他。</p>'
                    },
                    {
                        name:{
                            f:'黄忠',
                            l:'汉升',
                            s:'精力充沛的武士'
                        },
                        cv:'川津泰彦',
                        vu:'XMzM4MDQ5NzUxMg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/黄忠.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/黄忠1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/黄忠2.jpg'
                        },
                        des:'<p>久经战场的老将，具备老人特有的天真以及武将的严苛。</p><p>射箭高手，百发百中，因其勇猛身居五虎大将之一。</p>'
                    },
                    {
                        name:{
                            f:'姜维',
                            l:'伯约',
                            s:'继承龙遗志的麒麟儿'
                        },
                        cv:'菅沼久义',
                        vu:'XMzM4MDQ5NzUwOA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/姜维.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/姜维1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/姜维2.jpg'
                        },
                        des:'<p>青年武将，人称天水的麒麟儿。</p><p>作为诸葛亮继承人深受信任，受托兵法。于五丈原之战后，多次指挥军队进攻魏国。</p><p>因有着耿直的个性与强大的责任感，一直支持着如斜阳般衰弱的蜀国到最后。</p>'
                    },
                    {
                        name:{
                            f:'刘备',
                            l:'玄德',
                            s:'伟大的仁'
                        },
                        cv:'远藤守哉',
                        vu:'XMzM4MDQ5NzUxNg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/刘备.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/刘备1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/刘备2.jpg'
                        },
                        des:'<p>前汉中山靖王刘胜之后。</p><p>与结拜兄弟关羽、张飞共同于乱世战斗，重信义的名君。</p><p>比起理性来说，有时较重感情，因个性重情重义，吸引不少人投靠。</p>'
                    },
                    {
                        name:{
                            f:'刘禅',
                            l:'公嗣',
                            s:'继承仁之者'
                        },
                        cv:'松野太纪',
                        vu:'XMzM4MDU0NjE5Ng',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/刘禅.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/刘禅1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/刘禅2.jpg'
                        },
                        des:'<p>作为以自身魅力召集众多英雄的刘备之子，备受众人期待。</p><p> 不会立即行动，会深思熟虑后才下达判断，因此反应较为迟钝。</p><p>因过高的期待，反被他人误解为愚人。</p>'
                    },
                    {
                        name:{
                            f:'马超',
                            l:'孟起',
                            s:'热情的魂之刃'
                        },
                        cv:'服卷浩司',
                        vu:'XMzM4MDU0NzU5Ng',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/马超.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/马超1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/马超2.jpg'
                        },
                        des:'<p>西凉马腾长子。武艺高强，人称“锦马超”。</p><p>情感丰富充满热情的年轻武将，个性耿直，为了自我的信念，挥舞长枪，勇往直前。</p>'
                    },
                    {
                        name:{
                            f:'马岱',
                            l:'',
                            s:'开朗的辛苦人'
                        },
                        cv:'龙谷修武',
                        vu:'XMzM4MDU0ODE5Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/马岱.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/马岱1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/马岱2.jpg'
                        },
                        des:'<p>马超的堂兄弟。 自备曹操夺去家乡后，与马超共同投靠蜀国。</p><p>虽然饱经风霜，但是言行举止上都十分开朗。</p><p>深获诸葛亮信赖，成长为在对魏国战役中，被托付重任的一员大将。</p>'
                    },
                    {
                        name:{
                            f:'庞统',
                            l:'士元',
                            s:'古怪的奇才'
                        },
                        cv:'河内孝博',
                        vu:'XMzM4MDU0ODY5Ng',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/庞统.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/庞统1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/庞统2.jpg'
                        },
                        des:'<p>与诸葛亮师出同门，并称卧龙凤雏的天才军师。</p><p>行踪古怪，但却是个能看穿大局，直指事情本质的人。</p>'
                    },
                    {
                        name:{
                            f:'魏延',
                            l:'文长',
                            s:'异形的面具'
                        },
                        cv:'増谷康纪',
                        vu:'XMzM4MDU0OTE3Ng',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/魏延.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/魏延1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/魏延2.jpg'
                        },
                        des:'<p>淡定持续杀敌的狂战士。</p><p>其力量、外貌、言行，不分敌我皆感到畏惧。原为刘表手下，刘表死后，投降于刘备。</p><p>诸葛亮认为他具备反叛之相，但刘备很重用他。</p>'
                    },
                    {
                        name:{
                            f:'星彩',
                            l:'',
                            s:'年轻的守护者'
                        },
                        cv:'野田顺子',
                        vu:'XMzM4MDU0OTc0MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/星彩.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/张星彩1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/张星彩2.jpg'
                        },
                        des:'<p>张飞之女。诞生时正值乱世，在刘备旗下名将的守护下成长，自己决定参与战斗。 </p><p>以守护刘备之子刘禅为使命，肩负着蜀汉的未来命运。 </p><p>不似父亲般直来直往，十分冷静，不受感情起伏影响。</p>'
                    },
                    {
                        name:{
                            f:'徐庶',
                            l:'元直',
                            s:'烦恼的军师'
                        },
                        cv:'私市淳',
                        vu:'XMzM4MDU1MDM5Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/徐庶.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/徐庶1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/徐庶2.jpg'
                        },
                        des:'<p>司马徽门下弟子。为优秀军师亦为击剑高手。</p><p>过去曾帮忙打倒朋友之敌，却陷入被追讨的立场。</p><p>不光长于武艺，而且向学。之后投靠刘备，欲传达军略的重要性……</p>'
                    },
                    {
                        name:{
                            f:'月英',
                            l:'',
                            s:'龙之妻'
                        },
                        cv:'笠原留美',
                        vu:'XMzM4MDU1MTUwOA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/月英.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/月英1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/月英2.jpg'
                        },
                        des:'<p>诸葛亮之妻，黄承彦之女。</p><p>以武艺支持丈夫的智略，勇赴战场。</p><p>不光擅长武艺，上自天文下至地理、兵法亦无不知，于背后支持着诸葛亮。</p><p>平时贤淑，但赴战场时会勇敢战斗。</p>'
                    },
                    {
                        name:{
                            f:'张苞',
                            l:'',
                            s:'继承大志的豪勇武者'
                        },
                        cv:'阪口大助',
                        vu:'XMzM4MDU1MjIyOA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/张苞.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/张苞1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/张苞2.jpg'
                        },
                        des:'<p>张飞之子。有着不输父亲的高强武艺。</p> <p>责任感强，时时为他人着想。与结拜兄弟关兴一同活跃于北伐战斗。</p>'
                    },
                    {
                        name:{
                            f:'张飞',
                            l:'翼德',
                            s:'无比的豪勇'
                        },
                        cv:'挂川裕彦',
                        vu:'XMzM4MDU1MzA2MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/张飞.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/张飞1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/张飞2.jpg'
                        },
                        des:'<p>刘备、关羽的结义金兰，个性豪放磊落的战士。</p><p>曾单骑喝退曹操大军，纯真如孩童，因而个性过于急躁耿直。</p><p>嗜酒，也因此吃过败仗。</p>'
                    },
                    {
                        name:{
                            f:'赵云',
                            l:'子龙',
                            s:'年轻的龙，受仁之光所引导'
                        },
                        cv:'小野坂昌也',
                        vu:'XMzM4MDU1MzY4OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/赵云.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/赵云1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/赵云2.jpg'
                        },
                        des:'<p>重忠义，诚实守信的年轻武将。</p><p>为寻求乱世投身之主，遍访各地，最后因受刘备为人吸引，投靠其下。</p><p>之后成为蜀国五虎大将之一。 个性温和，于战场上，具备单骑闯入大军的斗志与勇气。</p>'
                    },
                    {
                        name:{
                            f:'周仓',
                            l:'',
                            s:'天下最速之大力士侍从'
                        },
                        cv:'泽城千春',
                        vu:'XMzM4MDU1NDMzMg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/周仓.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/周仓1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/周仓2.jpg'
                        },
                        des:'<p>原为黄巾军张宝的部下。</p><p>于卧牛山落草为寇时，与敬慕已久的关羽相会而成为其侍从。</p><p>据说其飞毛腿速度可比拟一日千里的赤兔马。力大善泳，为一名颇有贡献之将。</p>'
                    },
                    {
                        name:{
                            f:'夏侯姫',
                            l:'',
                            s:'温室之内向公主'
                        },
                        cv:'御沓优子',
                        vu:'',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/夏侯姫.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/夏侯姫1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/夏侯姫2.jpg'
                        },
                        des:'<p>张飞之妻，夏侯渊侄女。夏侯霸堂妹。</p><p>几乎足不出户，被视为掌上明珠，个性内向且害羞。</p><p>一次私下外出樵采时，偶遇张飞而成为其妻。</p>'
                    },
                    {
                        name:{
                            f:'诸葛亮',
                            l:'孔明',
                            s:'最强的先知'
                        },
                        cv:'小野坂昌也',
                        vu:'XMzM4MDU1NTEwOA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_7/诸葛亮.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/诸葛亮1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_8/诸葛亮2.jpg'
                        },
                        des:'<p>投身礼义的当代天才。</p><p>为回报三顾之礼，投靠刘备。以明智的判断力与公平无私的言行，深受全国人民的信赖。</p><p>手执白扇，神机妙算，掌握着战场先机。</p>'
                    }
                ]
            },
            wu:{
                nav:'吴',
                list:[
                    {
                        name:{
                            f:'程普',
                            l:'德谋',
                            s:'直言之贤者'
                        },
                        cv:'谷昌树',
                        vu:'XMzM4MDY1Mzg2NA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/程普.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/程普1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/程普2.jpg'
                        },
                        des:'<p>效忠孙家三代的老将。</p><p>致力为孙吴拓土开疆及安定领地，贡献良多。</p><p>身为勇猛武者长年于前线奋战，时而以其年长者的身分，担任参谋辅政。</p>'
                    },
                    {
                        name:{
                            f:'大乔',
                            l:'',
                            s:'虚幻坚强之花'
                        },
                        cv:'岛方淳子',
                        vu:'XMzM4MDY1NDQ2MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/大乔.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/大乔1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/大乔2.jpg'
                        },
                        des:'<p>乔玄之女，孙策之妻。</p><p>与妹妹小乔，并称二乔。</p><p>不好争斗，个性温和，但一心为支持孙策而奔赴战场。</p>'
                    },
                    {
                        name:{
                            f:'丁奉',
                            l:'承渊',
                            s:'孙吴第一的可怕硬汉'
                        },
                        cv:'中尾良平',
                        vu:'XMzM4MDY1NTA1Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/丁奉.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/丁奉1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/丁奉2.jpg'
                        },
                        des:'<p>孙吴将领。自第一场战斗开始便长年投身吴军，相当活跃。</p><p>因其严厉的面孔与异常粗壮的手腕，人们开始敬畏他。但实为喜爱美丽风景的天然诗人。</p>'
                    },
                    {
                        name:{
                            f:'甘宁',
                            l:'兴霸',
                            s:'磊落的侠客'
                        },
                        cv:'三浦祥朗',
                        vu:'XMzM4MDY1NTgwMA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/甘宁.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/甘宁1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/甘宁2.jpg'
                        },
                        des:'<p>腰间系着铃铛之故，人称“铃甘宁”。个性直爽的男儿。</p><p>投靠刘表、黄祖却未受重用。投身吴国后，活跃于赤壁之战与对魏国等战役。</p><p>个性急躁，容易与人起争执，但十分替人着想，受部下敬仰。</p>'
                    },
                    {
                        name:{
                            f:'韩当',
                            l:'义公',
                            s:'碎碎念的骁勇武将'
                        },
                        cv:'田中秀幸',
                        vu:'XMzM4MDY1NjM1Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/韩当.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/韩当1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/韩当2.jpg'
                        },
                        des:'<p>侍奉孙家三代的元勋。</p><p>原为辽西郡寒门，受孙坚赏识而受提拔，其后长年负责吴水军一翼。</p>'
                    },
                    {
                        name:{
                            f:'黄盖',
                            l:'公覆',
                            s:'干练的元勋'
                        },
                        cv:'稻田彻',
                        vu:'XMzM4MDY1NzE2MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/黄盖.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/黄盖1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/黄盖2.jpg'
                        },
                        des:'<p>孙坚举兵以来的元勋将领。</p><p>以一生于前线战斗之事为其生存意义的刚强之人。</p><p>豪爽的态度下，有着身经百战的自信。</p>'
                    },
                    {
                        name:{
                            f:'练师',
                            l:'',
                            s:'美丽的护卫'
                        },
                        cv:'神田朱未',
                        vu:'XMzM4MDY1NzkyNA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/练师.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/练师1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/练师2.jpg'
                        },
                        des:'<p>跟随孙尚香的女官。</p><p>为凋零的豪族步骘之女，因为武艺高强，担任孙尚香的护卫。</p>'
                    },
                    {
                        name:{
                            f:'凌统',
                            l:'公绩',
                            s:'无法憎恨的讽刺家'
                        },
                        cv:'松野太纪',
                        vu:'XMzM4MDY1ODM2OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/凌统.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/凌统1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/凌统2.jpg'
                        },
                        des:'<p>与父亲凌操以武将身分投靠孙吴。</p><p>在与黄祖君对战时，父亲被敌军甘宁击杀。其后，认定甘宁为世仇，憎恨着甘宁。</p><p>平常行事风格相当不留余地，但忠孝之心高于常人，成长为孙吴屈指可数的顶尖武将。</p>'
                    },
                    {
                        name:{
                            f:'鲁肃',
                            l:'子敬',
                            s:'威风堂堂的好汉'
                        },
                        cv:'楠大典',
                        vu:'XMzM4MTAyNDQ0MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/鲁肃.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/鲁肃1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/鲁肃2.jpg'
                        },
                        des:'<p>孙吴第二任都督，继承周瑜遗志，亦为吕蒙老师。</p><p>于复兴汉室为优先选项的时代中，提倡天下二分之计。</p>'
                    },
                    {
                        name:{
                            f:'陆逊',
                            l:'伯言',
                            s:'年轻的智勇之炎'
                        },
                        cv:'野岛健儿',
                        vu:'XMzM4MTAyNTI4MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/陆逊.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/陆逊1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/陆逊2.jpg'
                        },
                        des:'<p>凡事深思熟虑，以诚实为宗旨的清廉之将。</p><p>与吕蒙合作击破关羽，成功夺回荆州。 更于夷陵之战中以大都督身分指挥吴军，以计策大破刘备所率领的蜀国大军。</p><p>有着如少年般的活力与富有机智的聪明头脑。</p>'
                    },
                    {
                        name:{
                            f:'吕蒙',
                            l:'子明',
                            s:'智勇之士'
                        },
                        cv:'堀之纪',
                        vu:'XMzM4MTAyNjEyMA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/吕蒙.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/吕蒙1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/吕蒙2.jpg'
                        },
                        des:'<p>鲁莽但认真的努力家。</p><p>原为只靠一身武艺鲁莽作战的将领，受孙权谕示，奋发向学，成长为智勇兼备的名将。</p><p>见到此成果的前辈鲁肃非常感动，说出“非复吴下阿蒙”的称赞词句。</p><p>为人正直不阿，深受许多人的信赖。</p>'
                    },
                    {
                        name:{
                            f:'孙策',
                            l:'伯符',
                            s:'开朗的火焰'
                        },
                        cv:'河内孝博',
                        vu:'XMzM4MTAyNjc2NA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/孙策.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/孙策1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/孙策2.jpg'
                        },
                        des:'<p>孙坚长子，生气勃勃的斗将，人称“小霸王”。</p><p>个性自由豁达，亲切待人。</p><p>身边聚集了以幼时玩伴周瑜为首的优秀人才，打造出吴国的基业。</p>'
                    },
                    {
                        name:{
                            f:'孙坚',
                            l:'文台',
                            s:'猛虎之魂'
                        },
                        cv:'德山靖彦',
                        vu:'XMzM4MTAyNzQ0NA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/孙坚.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/孙坚1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/孙坚2.jpg'
                        },
                        des:'<p>孙武后裔，个性冷静开朗的勇将。</p><p>具备聪明君主、勇猛将领、温柔父亲等多样面貌。</p><p>于击退水贼一战成名后，活跃于黄巾讨伐征战中，亦担任长沙太守。</p><p>于反董卓同盟军中担任先锋，成功完成洛阳先锋之任务。</p>'
                    },
                    {
                        name:{
                            f:'孙权',
                            l:'仲谋',
                            s:'雄壮威武的虎子'
                        },
                        cv:'菅沼久义',
                        vu:'XMzM4MTAyODEwMA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/孙权.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/孙权1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/孙权2.jpg'
                        },
                        des:'<p>孙坚次子，孙策之弟。孙策称其为治国之才。</p><p>对于自身武勇没有自信，但是最终成长为英明的君主。</p>'
                    },
                    {
                        name:{
                            f:'孙尚香',
                            l:'',
                            s:'崇武的公主'
                        },
                        cv:'宇和川惠美',
                        vu:'XMzM4MTAyODgxMg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/孙尚香.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/孙尚香1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/孙尚香2.jpg'
                        },
                        des:'<p>孙坚之女，个性开朗充满活力，性格好强不服输。</p><p>长于武艺，在战场上总是身先士卒。</p><p>兼具高强武艺与过人美貌，人称“弓腰姬”。</p>'
                    },
                    {
                        name:{
                            f:'太史慈',
                            l:'子义',
                            s:'不屈的斗志'
                        },
                        cv:'挂川裕彦',
                        vu:'XMzM4MTAyOTk4NA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/太史慈.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/太史慈1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/太史慈2.jpg'
                        },
                        des:'<p>耿直重义理。为报答母亲受照顾之恩，解救北海太守孔融的危机。</p><p>其后投奔刘繇，后刘繇因败于孙策而归顺孙策。</p><p>以信义发挥武艺专长，借武艺完成大义为信念。</p>'
                    },
                    {
                        name:{
                            f:'小乔',
                            l:'',
                            s:'纯洁之花'
                        },
                        cv:'岛方淳子',
                        vu:'XMzM4MTAzMDc5Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/小乔.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/小乔1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/小乔2.jpg'
                        },
                        des:'<p>乔玄之女。周瑜之妻。与姐姐大乔并称“二乔”之美女。</p><p>天真纯洁，不知世事，甚至上战场，都是伴随周瑜以游玩心情来对待的。</p><p>因此，上战场打仗时亦具备过人的勇气。</p>'
                    },
                    {
                        name:{
                            f:'徐盛',
                            l:'文向',
                            s:'强硬男子汉'
                        },
                        cv:'新垣樽助',
                        vu:'XMzM4MTAzMTM0NA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/徐盛.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/徐盛1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/徐盛2.jpg'
                        },
                        des:'<p>孙权手下将领。当孙权继承孙策后，广纳人材，成为家臣。</p><p>参加赤壁、合肥攻略、荆州攻略等大型战役。</p><p>在曹丕进攻吴国时，以假城池城墙等方式，击退魏军，长期活跃在前线。</p>'
                    },
                    {
                        name:{
                            f:'周泰',
                            l:'幼平',
                            s:'无声之刃'
                        },
                        cv:'石川英郎',
                        vu:'XMzM4MTAzMjE2NA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/周泰.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/周泰1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/周泰2.jpg'
                        },
                        des:'<p>沉默寡言的男子汉。</p><p>原为水贼，之后决定归顺于孙策。于合肥之战中，以自身为盾，自乱战中救出孙权。</p><p>个性冷静，冷淡看待万事。为彻头彻尾的现实主义者。</p>'
                    },
                    {
                        name:{
                            f:'周瑜',
                            l:'公瑾',
                            s:'赤红热情'
                        },
                        cv:'吉水孝宏',
                        vu:'XMzM4MTAzMjk2MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/周瑜.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/周瑜2.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/周瑜1.jpg'
                        },
                        des:'<p>孙策结义兄弟，容貌甚佳，博得“美周郎”美名。</p><p>无出其右的顶尖将帅，率领吴军赢得无数场胜利。于文艺音乐等多方面都有出色的才华。</p><p>优美的举止下，隐藏着无与伦比的澎湃热情。</p>'
                    },
                    {
                        name:{
                            f:'朱然',
                            l:'义封',
                            s:'逆转的领导者'
                        },
                        cv:'柿原彻也',
                        vu:'XMzM4MTAzMzczNg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_1/朱然.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/朱然1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180204_zq_281_2/朱然2.jpg'
                        },
                        des:'<p>因为是孙权的学友而受重用的将领。</p><p>年纪轻轻就于山越讨伐和濡须口战役中崭露头角。</p><p>作为肩负吴国将来的下一代将领，凝聚大家的浓厚期待。</p>'
                    }
                ]
            },
            jin:{
                nav:'晋',
                list:[
                    {
                        name:{
                            f:'邓艾',
                            l:'士载',
                            s:'努力向上的将军'
                        },
                        cv:'小原雅人',
                        vu:'XMzM4MDQ4Nzc0NA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/001.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/邓艾1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/邓艾2.jpg'
                        },
                        des:'<p>魏国久经征战的名将。</p><p>原为文官，受司马懿赏识才能，分派至军机。</p><p>喜欢看地图，擅长活用地形的战法，活跃于对蜀的战争。</p>'
                    },
                    {
                        name:{
                            f:'郭淮',
                            l:'伯济',
                            s:'病弱的忠臣'
                        },
                        cv:'蒲田哲',
                        vu:'XMzM4MDQ4Nzc0OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/002.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/郭淮1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/郭淮2.jpg'
                        },
                        des:'<p>对蜀国战中活跃的将领。</p><p>因身体孱弱，常咳，赴战场时却能展现过人战绩。</p><p>为夏侯渊与司马懿恩人，对魏国的忠诚心比常人更强。</p>'
                    },
                    {
                        name:{
                            f:'贾充',
                            l:'公闾',
                            s:'冷酷的短刀'
                        },
                        cv:'高桥広树',
                        vu:'XMzM4MDQ4Nzc0MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/003.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/贾充1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/贾充2.jpg'
                        },
                        des:'<p>魏国名臣贾逵之子。身为武将，也是杰出政治家。</p><p>受司马懿提拔，以司马师、司马昭的心腹的身份活跃着。</p>'
                    },
                    {
                        name:{
                            f:'司马师',
                            l:'子元',
                            s:'无福消受天命的天才'
                        },
                        cv:'置鲇龙太郎',
                        vu:'XMzM4MDQ4OTAzNg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/004.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/司马师1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/司马师2.jpg'
                        },
                        des:'<p>司马懿长子。容貌典雅，颇具威严，富才气，是备受众人期待的继承人。</p><p>另一方面因独善其身的个性，周遭人皆以敬畏的想法看待他。</p>'
                    },
                    {
                        name:{
                            f:'司马懿',
                            l:'仲达',
                            s:'暗藏野心的鬼才'
                        },
                        cv:'置鲇龙太郎',
                        vu:'XMzM4MDQ4OTE4OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/005.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/司马懿1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/司马懿2.jpg'
                        },
                        des:'<p>天才军师。受曹操提拔担任军师。</p><p>是个自尊心超高的激情家，以理性压过激情的足智多谋为自身武器。</p><p>在曹操麾下，出谋划策带来多场魏国的胜利，受曹丕重用，掌握大权。</p>'
                    },
                    {
                        name:{
                            f:'司马昭',
                            l:'子上',
                            s:'奔放的次男'
                        },
                        cv:'岸尾大辅',
                        vu:'XMzM4MDQ4OTQ2MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/006.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/司马昭1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/司马昭2.jpg'
                        },
                        des:'<p>司马懿次子。 与完美的哥哥比起来，周遭的人总认为弟弟有些后天不足。</p> <p>做事粗心大意，得过且过，但面临重要局面时，决不会错看事物的本质。</p>'
                    },
                    {
                        name:{
                            f:'王元姬',
                            l:'',
                            s:'慧眼的美姬'
                        },
                        cv:'伊藤加奈惠',
                        vu:'XMzM4MDQ5MDQwOA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/007.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/王元姬1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/王元姬2.jpg'
                        },
                        des:'<p>魏国重臣王肃之女。</p><p>自幼聪慧，有胆识，周遭人总感叹说“若是男儿身的话就好了”。</p><p>以礼待人，温柔对待弱者，面对亲友会说出自己的真正心声。</p>'
                    },
                    {
                        name:{
                            f:'文鸯',
                            l:'次骞',
                            s:'仿佛英雄再世的年轻武士'
                        },
                        cv:'小野友树',
                        vu:'XMzM4MDQ5MDY4MA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/008.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/文鸯1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/文鸯2.jpg'
                        },
                        des:'<p>本名为文淑，文鸯是取自幼名阿鸯，魏将文钦之子。</p><p>具备超强武艺，在战场上的战绩受到世人绝赞，足匹赵云。</p>'
                    },
                    {
                        name:{
                            f:'夏侯霸',
                            l:'仲权',
                            s:'童颜的铠武者'
                        },
                        cv:'赤羽根健治',
                        vu:'XMzM4MDQ5MDk0OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/009.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/夏侯霸1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/夏侯霸2.jpg'
                        },
                        des:'<p>夏侯渊之子。</p><p>有着不输父亲的个性与看来和实际年龄不符、异常年轻的娃娃脸。为不让人看出年轻的外表，总是身披厚重冑甲。</p><p>作为名门夏侯一族的将领，颇受众人期待，后因魏国的政变，立场愈渐艰难。</p>'
                    },
                    {
                        name:{
                            f:'辛宪英',
                            l:'',
                            s:'开朗大方之贤女'
                        },
                        cv:'下地紫野',
                        vu:'XMzM4MDQ5MTU2OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/010.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/辛宪英1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/辛宪英2.jpg'
                        },
                        des:'<p>魏将辛毗之女，辛敞的姐姐，羊祜的叔母。</p><p>为人聪颖，数度以忠言挽救了家族的危机。</p>'
                    },
                    {
                        name:{
                            f:'张春华',
                            l:'',
                            s:'恐怖的贤妻良母'
                        },
                        cv:'浅野真澄',
                        vu:'XMzM4MDQ5MTg2OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/011.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/张春华1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/张春华2.jpg'
                        },
                        des:'<p>司马懿之妻，司马师、司马昭之母。</p><p>以贤女之名，声名远播，育有才子，作为贤妻良母，受人敬重。</p><p>时常面带微笑，但家族中无人不敬畏她。</p>'
                    },
                    {
                        name:{
                            f:'钟会',
                            l:'士季',
                            s:'早熟的策士'
                        },
                        cv:'会一太郎',
                        vu:'XMzM4MDQ5MjU5Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/012.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/钟会1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/钟会2.jpg'
                        },
                        des:'<p>年纪轻轻便大获成功的将领。</p><p>才华洋溢，积极参加战斗，但是因为年轻自信过剩，因此不太受老将领的信赖。</p><p>对于邓艾怀抱单方面的敌意。</p>'
                    },
                    {
                        name:{
                            f:'诸葛诞',
                            l:'公休',
                            s:'坚硬无比的坚物'
                        },
                        cv:'桐本琢也',
                        vu:'XMzM4MDQ5MzE3Ng',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_5/013.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/诸葛诞1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180202_zq_281_6/诸葛诞2.jpg'
                        },
                        des:'<p>诸葛一族视诸葛亮为“龙”，而诸葛瑾为“虎”。</p><p>诸葛诞被一族揶揄为“狗”，但透过脚踏实地的努力，在魏国获得高评价。认真，具强烈正义感。</p><p>但视野较小，不擅长需要考虑全盘大局的行动。</p>'
                    }
                ]
            },
            ta:{
                nav:'他',
                list:[
                    {
                        name:{
                            f:'陈宫',
                            l:'公台',
                            s:'胸怀二心的诙谐者'
                        },
                        cv:'宫崎宽务',
                        vu:'XMzM4MDU1NzQzMg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_1/陈宫.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/陈宫1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/陈宫2.jpg'
                        },
                        des:'<p>吕布军的军师。</p><p>平常时看似轻浮，实际其拥有非常大的野心，为了达成目的不顾任何牺牲。</p><p>原本是曹操的下属，因为考虑到在曹操手下无法实现自己的野心，所以转投吕布。</p>'
                    },
                    {
                        name:{
                            f:'貂蝉',
                            l:'',
                            s:'策谋的舞姬'
                        },
                        cv:'小松里歌',
                        vu:'XMzM4MDU1ODE1Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_1/貂蝉.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/貂蝉1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/貂蝉2.jpg'
                        },
                        des:'<p>绝世美女，擅长歌舞。</p><p>司徒王允视如己出抚养成人，以美色计接近董卓与吕布，成功使出“连环计”成功摧毁二人间的情谊。</p><p>在美丽的容貌下暗藏坚强的决心与过人觉悟，以媲美豪杰的热情，生存于乱世当中。</p>'
                    },
                    {
                        name:{
                            f:'董卓',
                            l:'仲颖',
                            s:'梦想酒池肉林的凶星'
                        },
                        cv:'堀之纪',
                        vu:'XMzM4MDU1ODkyOA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_1/董卓.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/董卓1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/董卓2.jpg'
                        },
                        des:'<p>原为西凉太守，回应何进的召集而上京。</p><p>趁混乱挟幼帝掌握政权。收猛将吕布为养子，挟武力废少帝执行迁都长安等暴政。</p><p>有着恶鬼的残虐与冷酷面貌的暴虐之徒，暴力且自我为尊的行动，引来乱世的恐怖。</p>'
                    },
                    {
                        name:{
                            f:'吕布',
                            l:'奉先',
                            s:'最强的鬼神'
                        },
                        cv:'稻田彻',
                        vu:'XMzM4MDU1OTYwOA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_1/吕布.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/吕布1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/吕布2.jpg'
                        },
                        des:'<p>武艺高强，擅长弓马术的猛将。</p><p>骑乘赤兔马，以鬼神般的高强武艺，人赞曰“人中吕布、马中赤兔”。</p><p>看出力量的最大价值，是个凭借对自身武艺的自信，无视社会伦理的硬汉。</p>'
                    },
                    {
                        name:{
                            f:'吕玲绮',
                            l:'',
                            s:'寂寥的凛凛战姬'
                        },
                        cv:'牛田裕子',
                        vu:'XMzM4MDU2MDQ3Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_1/吕玲绮.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/吕玲绮1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/吕玲绮2.jpg'
                        },
                        des:'<p>吕布之女。</p><p>有不输父亲的武艺，总是非常勇敢地率先奔赴前线战斗。</p><p>虽有勇于面对困难的坚韧之志，但是因受过去不好的经历所影响，有着害怕孤独的一面。</p>'
                    },
                    {
                        name:{
                            f:'孟获',
                            l:'',
                            s:'伟大的王'
                        },
                        cv:'幸野善之',
                        vu:'XMzM4MDU2MTExNg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_1/孟获.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/孟获1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/孟获2.jpg'
                        },
                        des:'<p>南中之王。</p><p>具备巨型身躯与强大力量，身为国王的同时也为最强的战士。</p><p>总是感情优先不太思考前后因果，也是个不似外观般勇猛的爱妻家、恐妻家。</p>'
                    },
                    {
                        name:{
                            f:'袁绍',
                            l:'本初',
                            s:'光芒万丈的名族'
                        },
                        cv:'龙谷修武',
                        vu:'XMzM4MDU2MTc1Ng',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_1/袁绍.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/袁绍1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/袁绍2.jpg'
                        },
                        des:'<p>出身名门袁家。为对抗专横的董卓，成为联军盟主。</p><p>董卓死后，认为应推举中原霸主，与小时玩伴的曹操共逐霸主宝座。</p><p>具备合乎名门身分的实力与势力，却因此反映其自尊心过强的弱点。</p>'
                    },
                    {
                        name:{
                            f:'张角',
                            l:'',
                            s:'聆听天意之人'
                        },
                        cv:'川津泰彦',
                        vu:'XMzM4MDU2MjYwOA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_1/张角.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/张角1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/张角2.jpg'
                        },
                        des:'<p>身为太平道教祖，向民众布道，趁乱世汇聚了广大民众的支持。</p><p>结成黄巾党，对抗汉王室。自称“天公将军”，掀动黄巾之乱。</p><p>超然的言语行动与特异的存在感，酝酿出独特的宗教感。</p>'
                    },
                    {
                        name:{
                            f:'祝融',
                            l:'',
                            s:'热情的火焰'
                        },
                        cv:'米本千珠',
                        vu:'XMzM4MDU2NTg1Mg',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_1/祝融.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/祝融1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/祝融2.jpg'
                        },
                        des:'<p>孟获妻子。称自己为传说火神祝融子孙，霸气的大姐大。</p><p>个性如名字般直来直往，充满攻击性，但是依然辅佐着总是直来直往不考虑后果，欠缺机运的孟获，使他能成为优秀的大王。</p>'
                    },
                    {
                        name:{
                            f:'董白',
                            l:'',
                            s:'大无畏之野蔷薇'
                        },
                        cv:'大关英里',
                        vu:'',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/董白.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/董白1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/董白2.jpg'
                        },
                        des:'<p>董卓孙女。</p><p>极受董卓疼爱，自小就拥有土地与财富。</p><p>个性任性且残酷，但在董卓面前则会装可爱。</p>'
                    },
                    {
                        name:{
                            f:'华雄',
                            l:'',
                            s:'狰狞之巨兽'
                        },
                        cv:'太田健介',
                        vu:'',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/华雄.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/华雄1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/华雄2.jpg'
                        },
                        des:'<p>董卓麾下猛将。</p><p>于汜水关抵抗孙坚以及袁绍等反董卓联合军。</p><p>据说其人身长九尺，虎体狼腰，豹头猿臂。</p>'
                    },
                    {
                        name:{
                            f:'袁术',
                            l:'公路',
                            s:'跋扈的名士'
                        },
                        cv:'平井启二',
                        vu:'',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/袁术.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/袁术1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180206_zq_281_1/袁术2.jpg'
                        },
                        des:'<p>东汉后将军，袁绍堂弟。</p><p>出身四世三公的名门，爱势贪财。</p><p>贪欲心重，虽拥玉玺称帝，却因恶政丧失民心。</p>'
                    },
                    {
                        name:{
                            f:'左慈',
                            l:'元放',
                            s:'明智的神仙'
                        },
                        cv:'佐藤正治',
                        vu:'XMzM4MDU2NjY0OA',
                        pic:{
                            f:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_1/左慈.jpg',
                            w:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/左慈1.jpg',
                            c:'http://img7.gamersky.com/zqimg/dgy/z358/tbs/20180203_zq_281_2/左慈2.jpg'
                        },
                        des:'<p>学会道术，善于操纵超然神迹。</p><p>忧心乱世，衷心祈祷满心仁德的刘备能重造安泰之世。</p>'
                    }
                ]
            }
        },
        //武器系统
        wqxt:{
            dl:{
                name:'锻炼武器',
                des:'<p>在装备的武器上镶嵌“宝玉”可以用以锻炼装备武器。</p><p>透过锻炼武器，可以随机强化攻击．防御等武将能力，并发动炎・冰・雷・风・斩・毒等具属性的攻击。</p><p>“宝玉”最多可以镶嵌６个，运用各种组合，可以制作出具备各种性能的武器。</p>',
                list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtdl01.jpg',txt:'宝玉可以装备在触发攻击３种与反应攻击３种，合计６个格子可以镶嵌。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtdl02.jpg',txt:'若用附加炎属性的武器，便能火烧敌人。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtdl03.jpg',txt:'若用附加冰属性的武器，便能冻结敌人。'}
                ]
            },
            gm:{
                name:'购买武器',
                des:'<p>可从都市等处的锻冶屋购买各种武器。</p><p>武器分下级・中级・上级３种类型，越高级性能越高，也因此非常昂贵。</p><p>入手方式除在锻冶屋购买之外，也可从名为“竹简”的武器配方，或者是取得制作所需的“素材”进行开发。</p><p>“竹简”与“素材”除可从古钱搜集家购买外，有时在地图上探索时也可取得。</p>',
                list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtgm01.jpg',txt:'巡回各处的锻冶屋，追求想要的武器也是种乐趣'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtgm02.jpg',txt:'曹操的得意武器“将剑”的下级武器'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtgm03.jpg',txt:'比下级武器防御力及攻击力更高，外观也更为奢华'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtgm04.jpg',txt:'孙坚的得意武器“九环刀”的中级武器'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtgm05.jpg',txt:'刘备的得意武器“双剑”的中级武器'}
                ]
            },
            dy:{
                name:'得意武器',
                des:'<p>操作的武将可以自由装备各种武器，但是若装备上武将的得意武器，不光可以施展出不同平常的固有动作外，具备攻击力也会更高、攻击范围更广等优点，发挥出比平常更高的性能。</p>',
                list:[
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtdy01.jpg',txt:'当张郃装备“圈”的时候，因为不是得意武器，所以会施展出一般动作。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtdy02.jpg',txt:'王异装备得意武器“圈”时，会成为迅速连续攻击的固有动作。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtdy03.jpg',txt:'吕布装备“狼牙棒”时，因为不是得意武器，所以会施展出一般动作。'},
                    {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/wqxtdy04.jpg',txt:'关银屏装备得意武器“狼牙棒”时，会朝空中丢掷武器，攻击敌人的固有动作。'}
                ]
            }
        },
        //动作系统
        dzxt:{
            tab1:{
                name:'易态连击系统',
                inner:[
                    {
                        name:'触发攻击',
                        des:'<p>变化敌人状态的一击。命中敌人后，施展结合预想流水攻击的连击。</p>',
                        list:[
                            {pic:'https://wx1.sinaimg.cn/mw1024/006N5ZR9ly1fnymwk21v4g30ob0do1l1.gif',txt:'将敌人击倒在地'},
                            {pic:'https://wx4.sinaimg.cn/mw1024/006N5ZR9ly1fnymwlud0mg30ob0do4qu.gif',txt:'将敌人击飞至空中'},
                            {pic:'https://wx4.sinaimg.cn/mw1024/006N5ZR9ly1fnymwjv5wzg30ob0do4qt.gif',txt:'使敌人昏厥一段时间'}
                        ]
                    },
                    {
                        name:'反应攻击',
                        des:'<p>依玩家与敌人状况、时机等变化的攻击招式。可以创造对玩家有利的局面。</p>',
                        list:[
                            {pic:'https://wx1.sinaimg.cn/mw1024/006N5ZR9ly1fnyn0vvhigg30ob0do4qw.gif',txt:'反击：对欲攻击自己的敌人进行反击。'},
                            {pic:'https://wx3.sinaimg.cn/mw1024/006N5ZR9ly1fnyn0gn705g30ob0do7wk.gif',txt:'驱离攻击：能将附近敌人驱离一段距离的攻击。'},
                            {pic:'https://wx3.sinaimg.cn/mw1024/006N5ZR9ly1fnyn0psh50g30ob0dokjp.gif',txt:'冲刺攻击：一口气逼近远处敌人的攻击。'},
                            {pic:'https://wx2.sinaimg.cn/mw1024/006N5ZR9ly1fnyn0v1a98g30ob0do4qv.gif',txt:'击落攻击：能将空中的敌人击落地面的攻击。'},
                            {pic:'https://wx3.sinaimg.cn/mw1024/006N5ZR9ly1fnyn0suxnhg30ob0do4qu.gif',txt:'破防攻击：对防御中的敌人施展的攻击，可瓦解敌人的防御。'},
                            {pic:'https://wx4.sinaimg.cn/mw1024/006N5ZR9ly1fnyn07fugsg30ob0do4qr.gif',txt:'奇袭攻击：在未被敌人察觉的状态下，一口气逼近敌人给予大伤害的攻击。'},
                            {pic:'https://wx4.sinaimg.cn/mw1024/006N5ZR9ly1fnyn0sbpzog30ob0do7wm.gif',txt:'终结攻击：对敌人给与一定程度的伤害后会施展的攻击，能确实击破敌人。'}
                        ]
                    },
                    {
                        name:'流水攻击',
                        des:'<p>依通常状态、腾空状态、倒地状态等敌人的状态随时变化的攻击招式。以迅雷不及掩耳的连续攻击，给予敌人大量伤害。</p>',
                        list:[
                            {pic:'https://wx1.sinaimg.cn/mw1024/006N5ZR9ly1fnyn5eo5zmg30ob0do7wl.gif',txt:'当攻击对象位于地面时'},
                            {pic:'https://wx2.sinaimg.cn/mw1024/006N5ZR9ly1fnyn5hmfkyg30ob0do1l2.gif',txt:'攻击对象倒地时'},
                            {pic:'https://wx4.sinaimg.cn/mw1024/006N5ZR9ly1fnyn5ii4zdg30ob0doqva.gif',txt:'攻击对象为昏厥状态时 '},
                            {pic:'https://wx3.sinaimg.cn/mw1024/006N5ZR9ly1fnyn5f15y1g30ob0doe85.gif',txt:'攻击对象位于空中时'}
                        ]
                    },
                    {
                        name:'属性攻击',
                        des:'<p>在锻炼武器中装配宝玉，使用不同的属性攻击更具战术性。</p>',
                        list:[
                            {pic:'https://wx2.sinaimg.cn/mw1024/006N5ZR9ly1fnyn76kv3yg30ob0dokjs.gif',txt:''}
                        ]
                    },
                    {
                        name:'特殊技',
                        des:'<p>发动各武将各自固有的强力攻击。</p>',
                        list:[
                            {pic:'https://wx2.sinaimg.cn/mw1024/006N5ZR9ly1fnyn801lc8g30ob0do4qv.gif',txt:''}
                        ]
                    }
                ]
            },
            tab2:{
                name:'应变动作',
                inner:[
                    {
                        name:'攀登',
                        des:'<p>针对存在在野外的对象，或是眼前宽广的河川等地形变化，适时采取各种行动。除利用钩绳攀登绝壁、在大河中游泳等关于移动方面的行动外，还有战斗时以火焰箭引爆油壶、运用墙壁三角跳跃等动作，甚至还有在河畔钓鱼等动作，藉由应变动作系统的导入，大幅提升人物的自由度。</p>',
                        list:[
                            {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/dzxt21.jpg',txt:'利用勾绳攀登绝壁'}
                        ]
                    },
                    {
                        name:'三角跳',
                        des:'<p>针对存在在野外的对象，或是眼前宽广的河川等地形变化，适时采取各种行动。除利用钩绳攀登绝壁、在大河中游泳等关于移动方面的行动外，还有战斗时以火焰箭引爆油壶、运用墙壁三角跳跃等动作，甚至还有在河畔钓鱼等动作，藉由应变动作系统的导入，大幅提升人物的自由度。</p>',
                        list:[
                            {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/dzxt22.jpg',txt:'利用墙壁三角跳'}
                        ]
                    },
                    {
                        name:'火焰箭',
                        des:'<p>针对存在在野外的对象，或是眼前宽广的河川等地形变化，适时采取各种行动。除利用钩绳攀登绝壁、在大河中游泳等关于移动方面的行动外，还有战斗时以火焰箭引爆油壶、运用墙壁三角跳跃等动作，甚至还有在河畔钓鱼等动作，藉由应变动作系统的导入，大幅提升人物的自由度。</p>',
                        list:[
                            {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/dzxt23.jpg',txt:'用火焰箭引爆油壶'}
                        ]
                    },
                    {
                        name:'游泳',
                        des:'<p>针对存在在野外的对象，或是眼前宽广的河川等地形变化，适时采取各种行动。除利用钩绳攀登绝壁、在大河中游泳等关于移动方面的行动外，还有战斗时以火焰箭引爆油壶、运用墙壁三角跳跃等动作，甚至还有在河畔钓鱼等动作，藉由应变动作系统的导入，大幅提升人物的自由度。</p>',
                        list:[
                            {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/dzxt24.jpg',txt:'在大河中游泳'}
                        ]
                    },
                    {
                        name:'钓鱼',
                        des:'<p>针对存在在野外的对象，或是眼前宽广的河川等地形变化，适时采取各种行动。除利用钩绳攀登绝壁、在大河中游泳等关于移动方面的行动外，还有战斗时以火焰箭引爆油壶、运用墙壁三角跳跃等动作，甚至还有在河畔钓鱼等动作，藉由应变动作系统的导入，大幅提升人物的自由度。</p>',
                        list:[
                            {pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/dzxt25.jpg',txt:'在河畔钓鱼'}
                        ]
                    }
                ]
            }
        },
        //剧本
        jb:[
            {cpt:'第一章',tit:'黄巾平定',time:'184年',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/01_chara.png',con:'汉末，世道大乱，天灾人祸，民不聊生。此时，名为张角的男人出现，在冀州创立太平道，救济百姓，俘获民心。中平元年，张角起兵，号称黄巾军。朝廷欲镇压叛乱，却不断败北，延续四百年之久的汉王朝即将落幕。'},
            {cpt:'第二章',tit:'洛阳争乱',time:'190年',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/02_chara.png',con:'张角败北，黄巾乱终。但是乱世依然继续，国都洛阳，十常侍宦官与外戚对立。西凉董卓趁机兵入洛阳，自立太尉，独断朝纲，诸侯对此感到强烈的危机感。'},
            {cpt:'第三章',tit:'群雄割据的开始',time:'194年',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/03_chara.png',con:'诸侯奉袁绍为盟主，成功击倒董卓。逃到长安的董卓，被背叛的吕布击杀。诸侯蠢蠢欲动，袁绍和袁术对立，诸侯纷纷站队，但却暗藏野心，暗流涌动。'},
            {cpt:'第四章',tit:'中原制霸者',time:'197年',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/04_chara.png',con:'曹操迎汉献帝到许昌，获得大义。另一方面，袁术手握玉玺，意欲称帝，但却遭袁绍讨伐。'},
            {cpt:'第五章',tit:'卧龙觉醒',time:'200年',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/05_chara.png',con:'曹操于官渡击败袁绍，袁家终至灭亡。曹操成为最接近天下的男人。另一方面，江东孙氏孙权继承父兄基业，但无力进兵中原。刘备尚未有自己的领地，只能依附荆州刘表，在这里新的命运正在等待着他。'},
            {cpt:'第六章',tit:'赤壁大战',time:'208年',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/06_chara.png',con:'曹操攻下荆州，逼近孙吴的扬州。面对前所未见的强敌，孙吴陷入是战是降的天人交战。而被逐出荆州的刘备，得到卧龙诸葛亮的辅佐。面对如此危机，天才军师的计策是……'},
            {cpt:'第七章',tit:'三国鼎立',time:'208年',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/07_chara.png',con:'赤壁之战，孙刘获胜。曹操放弃南进，兵退许昌。孙权为扩大江东领地，开始行动。而诸葛亮，为拥护刘备成为一国之主，而默默地开始行动。'},
            {cpt:'第八章',tit:'三国鸣动',time:'215年',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/08_chara.png',con:'刘备兵进巴蜀，获得国土，至此三国鼎立。为了打破平衡，魏国拿下张鲁的汉中之地，吴军趁机兵发合肥。蜀国也攻入了夏侯渊、张郃防守的汉中。曹操亲身远赴汉中，企图阻止蜀国攻势。'},
            {cpt:'第九章',tit:'荆州激斗',time:'219年',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/09_chara.png',con:'刘备击退进攻汉中的曹操，自称汉中王。防守荆州的关羽得信起兵伐魏，兵进樊城。但是孙吴却在此意图谋取荆州。'},
            {cpt:'第十章',tit:'霸道与王道之路',time:'222年',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/10_chara.png',con:'关羽身死麦城，吴蜀同盟破裂，孙刘联合抗曹的态势也荡然无存。另一方面，曹操将王的霸道托付给儿子曹丕，离开人世。三国鼎立之势，迎来了新的局面。'}
        ],
        //版本
        bb:[
            {name:'普通版',url:'https://store.playstation.com/zh-hans-hk/home/games#!/dynasty-warriors-9-pre-order/cid=HP0106-CUSA09656_00-ASIAPLACEHOLDER0',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/bb01pc.png',wappic:'http://img7.gamersky.com/zqimg/dgy/z358/com/bb01wap.png'},
            {name:'特典版',url:'https://shop.gamecity.ne.jp/var/limited/2017/smusou8/?_ga=2.143770805.144597840.1517905796-1413690781.1507797430',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/bb02pc.png',wappic:'http://img7.gamersky.com/zqimg/dgy/z358/com/bb02wap.png'},
            {name:'一骑当千典藏版',url:'https://shop.gamecity.ne.jp/var/limited/2017/smusou8/?_ga=2.248760711.144597840.1517905796-1413690781.1507797430',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/bb03pc.png',wappic:'http://img7.gamersky.com/zqimg/dgy/z358/com/bb03wap.png'},
            {name:'数字豪华版',url:'https://store.playstation.com/zh-hans-hk/product/HP0106-CUSA09656_00-ASIAPLACEHOLDER1',pic:'http://img7.gamersky.com/zqimg/dgy/z358/com/bb04pc.png',wappic:'http://img7.gamersky.com/zqimg/dgy/z358/com/bb04wap.png'}
        ]
    }
};