var pageConfig = {
    countid:'987115',
    bgm:{
        txt:['打开声音','关闭声音'],
        start:'http://image.gamersky.com/webimg13/zhuanti/codolts/media/bgm.mp3'
    },
    userMute:true,
    volClk:true,
    isCommOpen:false,
    isVideoPlaying:false,
    addedComment:false,
    bgmvol:1,
    imglist:{
        loading:{
            logo1:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/ld-logo.png',
            logo2:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/ld-logo-g.png'
        },
        ldPage:{
            vd:'http://image.gamersky.com/webimg13/zhuanti/codolts/media/loading.mp4'
        },
        begin:{
            bg:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/bg_begin.jpg',
            gs:'http://www.gamersky.com/',
            gf:'http://codol.qq.com/'
        },
        page04:{
            bg:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/bg_04.jpg',
            para1:'动视暴雪出品，Raven工作室倾力打造，根据全球超人气《使命召唤》系列改编的新一代跑轰枪战网游。以充满动感的真实动作为基础，融入高科技大杀器和武器自定义系统，搭配丰富的战术装备，让你灵活在战场上移动，用百般方式自由杀敌，感受高速激情的团战。',
            para2:'Raven 从1990年创立以来，核心追求是最高质量的视觉效果和最佳的游戏玩法。RAVEN早在1997年就被动视收购，曾参与过《使命召唤：黑色行动》、《使命召唤：现代战争3》等的制作，如今接手并主导《使命召唤Online》研发，为中国玩家不断带来创新的玩法和游戏体验。'
        },
        page05:{
            bg:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/bg_05.jpg',
            tab:[
                [
                    {
                        nav:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s511n.jpg',
                        icon:'icon-n1',
                        tit:'经典爆破',
                        pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s511.jpg',
                        para:'玩家分为进攻和防守两个阵营，进攻方获得炸弹后，在规定的时间内，以摧毁地图中两个目标点或歼灭所有的防守方队员为胜利条件，而防守方则防御对方，保护目标不被摧毁或歼灭所有的攻击方队员获得胜利。在一场经典爆破中达到一定局数后将马上换边。'
                    },
                    {
                        nav:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s512n.jpg',
                        icon:'icon-n2',
                        tit:'冲锋团竞',
                        pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s512.jpg',
                        para:'经典的团队竞技模式，玩家将分为两个阵营对抗，率先达到杀敌目标分数，或者游戏时间结束后分数高的一方玩家阵营获得胜利，这个模式规则非常简单，适合新手快速熟悉与上手游戏。'
                    },
                    {
                        nav:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s513n.jpg',
                        icon:'icon-n3',
                        tit:'激光大乱斗',
                        pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s513.jpg',
                        para:'Raven工作室全新原创PVP模式，带你轻松玩转未来高科技枪战。每一位战士，都统一配备相同的激光枪和被动技能，光枪拥有极限的攻击力，无射程、无弹药限制，击中目标将一击必杀，枪法和身法将是王者的制胜之道。'
                    },
                    {
                        nav:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s514n.jpg',
                        icon:'icon-n4',
                        tit:'首领团竞',
                        pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s514.jpg',
                        para:'在这个模式里，每个人都有机会成为重装首领，带领队友一起突破重围。采用了动态随机系统，当前首领阵亡后将选择任意一位队友变身，可以“一秒当大哥”。首领具备强大的防御力和武器，可以为队友提供可靠的支援，像一部坦克般带领所有人前进。'
                    },
                    {
                        nav:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s515n.jpg',
                        icon:'icon-n5',
                        tit:'战术团竞',
                        pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s515.jpg',
                        para:'使命召唤特有的团队竞技模式，玩家将在地图中随机重生，向敌人发起进攻。率先达到杀敌数或游戏时间内杀敌更多一方将获得胜利。'
                    }
                ],
                [
                    {
                        nav:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s521n.jpg',
                        icon:'icon-n1',
                        tit:'生存模式',
                        pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s521.jpg',
                        para:'一个强调团队配合的模式，玩家之间相互合作来阻击敌人一波波猛烈的攻势。连续杀敌、秒杀、击落敌方直升机或者是救起受伤倒地的队友等，都会获得花色不同的扑克牌，可兑换武器弹药、技能、各种连杀技能、防弹背心甚至更换自己的战术背包。'
                    },
                    {
                        nav:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s522n.jpg',
                        icon:'icon-n2',
                        tit:'营救模式',
                        pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s522.jpg',
                        para:'《使命召唤》系列历史上的全新独创内容，在《使命召唤Online》中首次登场！6名玩家组成小队深入机械僵尸环伺的占领区，去搜索那里的幸存者并引导他们撤离！等待着玩家的除了有成群结队的“游荡者”机械僵尸、“生化猎犬”之外，“末日先遣舰”将会成为玩家撤离的最后障碍！'
                    },
                    {
                        nav:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s523n.jpg',
                        icon:'icon-n3',
                        tit:'僵尸围城',
                        pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s523.jpg',
                        para:'可以和朋友一起组队，通力合作冰神深入机械僵尸环伺的荒废都市，解开机械僵尸起源之谜！除了紧张刺激的僵尸突围，更有武器升级系统助你战斗！'
                    },
                    {
                        nav:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s524n.jpg',
                        icon:'icon-n4',
                        tit:'战车突围',
                        pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s524.jpg',
                        para:'原创PVE模式“战车突围”全球首发！你将面对危险的爆炸僵尸和超巨型BOSS“异变暴君”——它拥有多种可怖形态，具备跟踪导弹、圆弧飞碟甚至是制造分身等强力攻击方式。当然你也有新的伙伴“绞肉战车”，快与你的好友组队，一同探索如何击败机械僵尸巨怪“异变暴君”！'
                    },
                    {
                        nav:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s525n.jpg',
                        icon:'icon-n5',
                        tit:'空中收割者',
                        pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s525.jpg',
                        para:'中国独占PVE模式，Raven工作室倾力打造。在全新的地图“落日之城”里，你将在重型直升机上，与史诗般的怪物狂潮展开激烈战斗。超巨型的暴君、高度进化的末日战舰、机械炮塔、人类变异僵尸、爆炸僵尸等凶猛怪物悉数集结，展开一波又一波的攻击。'
                    }
                ],
                {
                    icon:'icon-arr',
                    tit:'单人剧情',
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s531.jpg',
                    para:'恐怖组织“裂变力量”阴谋重重，神秘部队暗影军团暗涌流动。一次行动中，“裂变力量”手里的危险原料“115元素”被暗影军团盗走，后者企图利用其合成大规模杀伤生化武器。你将加入141特遣队，与伟大的战士肥皂、幽灵一起解除这次威胁，探寻暗影军团的行踪，经历曲折多变的故事。追查的过程中，141特遣队与暗影军团激烈交火，队中的一名成员神秘失踪。幽灵获得情报后擅自离队行动，随后裂变力量也被卷入这场战斗中，到底谁是其中的幕后黑手？幽灵和失踪队员去向如何？精彩的剧情，等你来翻篇。'
                }
            ]
        },
        page06:{
            bg:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/bg_06.jpg',
            tab:[
                {
                    tid:1,
                    tit:'炸弹小飞机',
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s601.png',
                    vid:'h0017zyokuv',
                    tip:'6级解锁 / 4连杀可使用',
                    des:'带自动追踪装置的新一代攻击型无人机。放出后可以自动索敌，攻击地面和天空的目标，对敌人、地方空中支援都是新的威胁。'
                },
                {
                    tid:2,
                    tit:'空地导弹',
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s602.png',
                    vid:'a00195lyh0p',
                    tip:'5连杀可使用',
                    des:'你将使用专属控制电脑，遥控并操纵一枚从空中发射的导弹，在其下落到地面时可以自由调整轰炸地点，可实现范围性的打击。'
                },
                {
                    tid:3,
                    tit:'哨戒机枪',
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s603.png',
                    vid:'s00195pdqpa',
                    tip:'10级解锁 / 5连杀可使用',
                    des:'空投一个能够任意安置在战场中的自动机枪，其可以自动扫描并感应攻击范围内的敌人，一旦发现将自动射击将其歼灭。'
                },
                {
                    tid:4,
                    tit:'攻击直升机',
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s604.png',
                    vid:'i0019a9cqho',
                    tip:'7连杀可使用',
                    des:'呼叫一架攻击直升机到战场上进行武装支援，直升机将持续在空中盘旋索敌，对于暴露在室外的敌人杀伤力巨大。'
                },
                {
                    tid:5,
                    tit:'无畏战士',
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s605.png',
                    vid:'a0016k9xiqy',
                    tip:'44级解锁 / 11连杀可使用',
                    des:'玩家将穿上重型装甲，变成防御力超强的魁梧战士，持续时间无限。在无畏战士状态下，奔跑速度会慢，但防御力和承受伤害比普通战士高出一个级别。可以使用重机枪大火力压制，是提供掩护和支援的好帮手。'
                },
                {
                    tid:6,
                    tit:'空中炮艇',
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s606.png',
                    vid:'b0016722b5t',
                    tip:'63级解锁 / 11连杀可使用',
                    des:'传奇控场大杀器空中炮艇，让你呼叫重型空对地攻击机从空中尽情扫荡敌人。搭载25毫米6管航炮、40毫米自动炮、105毫米人工装填式榴弹炮，可长时间停留空中，对地面车队、部队、建筑可造成致命打击，被称为“空中死神”。'
                }
            ]
        },
        page07:{
            bg:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/bg_07.jpg',
            moreUrl:'http://codol.gamersky.com/data/',
            tab:[
                {
                    tid:1,
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s701.png',
                    tit:'C4炸药包',
                    des:'C4可塑炸药，结合专用引信引爆，可以抛出粘在墙壁、地面、天花板上，在地面上手动遥控引爆，威力极强。'
                },
                {
                    tid:2,
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s702.png',
                    tit:'阔剑地雷',
                    des:'威名赫赫的定向杀伤地雷，靠单片大范围杀伤目标，但只能感应前方一定角度内的移动物体，威慑作用巨大。'
                },
                {
                    tid:3,
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s703.png',
                    tit:'粘性手雷',
                    des:'带黏性的SEMTEX炸药，掷出后会粘着在其触碰到的第一个物体表面并延时起爆。'
                },
                {
                    tid:4,
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s704.png',
                    tit:'十字弩',
                    des:'复古系兵器之一，射速较慢，弓箭在击中任何物体后会延时爆炸，一击必杀。'
                },
                {
                    tid:5,
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s705.png',
                    tit:'飞刀',
                    des:'可以直接投掷，飞刀呈一定抛物线，拥有一击必杀的威力，而且可以回收重复使用。'
                },
                {
                    tid:6,
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s706.png',
                    tit:'自由之剑',
                    des:'设计原型基于15世纪广泛使用的双手大剑，极长的剑身和明亮的锋刃，象征着为自由战斗的勇士精神。双手重剑在手，助你在战斗中无往不利。'
                },
                {
                    tid:7,
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s707.png',
                    tit:'标枪导弹',
                    des:'著名的“发射后不管”式单兵反坦克导弹，启动后需要预先锁定目标，导弹发射后将从天而降打击目标，对敌人和直升机等载具都具备杀伤力。'
                },
                {
                    tid:8,
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s708.png',
                    tit:'震撼弹',
                    des:'迟滞敌人行动并使其失去方向感，可造成少量伤害。'
                },
                {
                    tid:9,
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s709.png',
                    tit:'盾牌',
                    des:'精英部队专用的特殊材料盾牌，可以防御任何子弹，一定程度上可以保护不受爆炸伤害，是配合支援的神器之一。'
                },
                {
                    tid:10,
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s710.png',
                    tit:'贝蒂跳雷',
                    des:'经典反步兵地雷，被敌人触发后会弹射至半空中引爆，威力极强。如果及时卧倒可以部分减少受到的爆炸伤害。'
                },
                {
                    tid:11,
                    pic:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/s711.png',
                    tit:'蝙蝠镖',
                    des:'万圣节专属武器，投掷后一击必杀，可以捡回反复使用。'
                }
            ]
        },
        page08:{
            bg:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/bg_08.jpg'
        },
        end:{
            bg:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/bg_end.jpg',
            para:'CODOL由动视暴雪研发，以久负盛名的《Call of Duty》系列为题材，集合了《Call of Duty》全系列最受欢迎的元素制作的第一人称视角射击游戏网游，绝对是喜欢FPS游戏的玩家不可错过的大作！',
            urlZq:'http://codol.gamersky.com/',
            urlDn:'http://codol.qq.com/download.shtml'
        },
        comm:{
            bg:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/bg_comm.jpg'
        },
        p360:{
            bg:'http://image.gamersky.com/webimg13/zhuanti/codolts/pic/bg_360.jpg',
            url:'http://60.55.47.163:81/dutycall/'
        },
        vdend:{
            vd1:'',
            vd2:'http://image.gamersky.com/webimg13/zhuanti/codolts/media/endvd.mp4'
        }
    }
};
//预加载图片
 var preLoadPicsLists = {
     list1: [
         pageConfig.imglist.begin.bg,
         pageConfig.imglist.page04.bg,
         pageConfig.imglist.comm.bg

     ],
     list2:[
         pageConfig.imglist.p360.bg,
         pageConfig.imglist.page06.bg,
         pageConfig.imglist.page07.bg,
         pageConfig.imglist.page08.bg,
         pageConfig.imglist.end.bg
     ]
 };