var gloCfg = {
    imgPath:'ztimages/',
    flowPath:'ztimages/flow/',
    mediaPath:'ztmedia/',
    countid:512179,
    url:{
        channel:'http://www.gamersky.com/zl/preview/',
        club:'http://i.gamersky.com/club/8',
        ku:'http://ku.gamersky.com/2016/God-of-War-IV/',
        pc:'http://www.gamersky.com/review/201804/1033478.shtml'
    },
    page:{
        zoom:1
    }
};
var stateStore = {
    fixedNavShow:false,
    taskProgress:0,
    isTold:false,
    toldOver:false
};
var pageAutoTimer;
var pageConfig = {
    countid:'512179',
    bgm:{
        txt:['打开声音','关闭声音'],
        nowplay:'',
        start:'ztmedia/bgm.mp3',
        task1:'ztmedia/bgm-helicopter1.mp3'
    },
    userMute:true,
    volClk:true,
    isCommOpen:false,
    isVideoPlaying:false,
    addedComment:false,
    addedFixed:false,
    raceVd:'dbcb4aefe3',
    formJs:false,
    audPlayVol:0.1,
    bgmvol:1,
    pages:{
        loading:{
            logo1:'ztimages/ld-logo.png',
            logo2:'ztimages/ld-logo-g.png',
            ld:'ztimages/ld-icon.png'
        },
        pgStart:{
            slogan:gloCfg.imgPath+'start-slogan.png',
            video:gloCfg.mediaPath + 'start-vd.mp4',
            transit:{
                video:{
                    player:'se',
                    vid:'o8qoh',
                    bkvid:'XMzQ4OTI1MjUwMA',
                    controls:false
                }
            }
        },
        pgMenu:{
            bg:gloCfg.imgPath+'menu-bg.jpg',
            nav:[
                {
                    name:'逮捕令',
                    open:false,
                    tro:gloCfg.imgPath+'menu-task1.png'
                },
                {
                    name:'无路可逃',
                    open:false,
                    tro:gloCfg.imgPath+'menu-task2.png'
                },
                {
                    name:'杀出重围',
                    open:false,
                    tro:gloCfg.imgPath+'menu-task3.png'
                },
                {
                    name:'地下基地',
                    open:false,
                    tro:gloCfg.imgPath+'menu-task4.png'
                }
            ]
        },
        pgVersion:{
            bg:gloCfg.imgPath+'version-bg.jpg',
            tabs:[
                {
                    id:0,
                    name:'游戏版本',
                    pic:gloCfg.imgPath+'version-ver.png',
                    buy:[
                        {
                            name:'数字标准版',
                            url:'https://store.ubi.com/cn/game?dwvar_591567f6ca1a6460388b4568_Platform=pcdl&pid=591567f6ca1a6460388b4568'
                        },
                        {
                            name:'数字豪华版',
                            url:'https://store.ubi.com/cn/game?dwvar_591486f90c8ee43e228b4567_Platform=pcdl&pid=591486f90c8ee43e228b4567\n'
                        },
                        {
                            name:'数字黄金版',
                            url:'https://store.ubi.com/cn/game?dwvar_591980f94e0165260a8b4568_Platform=pcdl&pid=591980f94e0165260a8b4568'
                        }
                    ]
                },
                {
                    id:1,
                    name:'季票',
                    pic:gloCfg.imgPath+'version-st.png',
                    swp:[
                        {
                            name:'季票1',
                            video:{
                                player:'se',
                                vid:'2fu3h',
                                bkvid:'XMzQ4OTI1MzgxNg',
                                poster:gloCfg.imgPath+'version-st-pst1.png'
                            }
                        },
                        {
                            name:'季票2',
                            video:{
                                player:'se',
                                vid:'ctjqa',
                                bkvid:'XMzQ4OTI1NDM5Ng',
                                poster:gloCfg.imgPath+'version-st-pst2.png'
                            }
                        },
                        {
                            name:'季票3',
                            video:{
                                player:'se',
                                vid:'124vn',
                                bkvid:'XMzQ4OTI1NDEzNg',
                                poster:gloCfg.imgPath+'version-st-pst3.png'
                            }
                        }
                    ]
                },
                {
                    id:2,
                    name:'游戏配置',
                    pic:gloCfg.imgPath+'version-cfg.png'
                }
            ]
        },
        pgEnd:{
            video:gloCfg.mediaPath+'end-vd.mp4',
            edit:'<h5>内容策划</h5><p>观海、小熊桑、Catcher</p><h5>视觉设计</h5><p>Drakedooog、皮皮、MrrrTian</p>'
        },
        pgComm:{
            bg:gloCfg.imgPath+'comm-bg.jpg'
        }
    },
    flow:{
        task1:{
            bg:gloCfg.flowPath+'task1-bg.jpg',
            txt:'<p>作为希望郡的新任副警长，你现在面临的最大问题是：警徽形同虚设，伊甸之门计划的教徒们已经严重威胁了希望郡的治安。而你，此行就是要逮捕邪教首领：约瑟夫·席德。</p>'
        },
        task101:{
            bg:gloCfg.flowPath+'task101-bg.jpg',
            dia:[
                {
                    txt:'<p>喂，菜鸟，菜鸟！</p>'
                },
                {
                    txt:'<p>别浪费时间看录像了，准备审问约瑟夫本人吧。</p>'
                }
            ]
        },
        task102:{
            bg:gloCfg.flowPath+'task102-bg.jpg',
            dia:[
                {
                    txt:'<p>看外面，我靠，真是个狂妄的疯子。</p>'
                },
                {
                    txt:'<p>“圣父”约瑟夫·席德的巨型雕像，据传他来自格鲁吉亚南方的偏远小镇，此前一直过着颓废的生活，直到有一天的清晨他听到一阵轻声低语，那低语向他预示了毁灭日的临近，并感召他“去拯救尽可能多的灵魂，无论他是否愿意被拯救。”</p><p>约瑟夫聚集了那些被社会所遗弃的可怜人、被剥夺公民权的罪犯以及无视法律的疯子，在蒙大拿州的希望郡组建了“新伊甸园”。</p><p>自称为“圣父”的约瑟夫·席德宣称自己受神的旨意拯救苍生，然而拯救的方式并不是仁爱与忏悔，只有极尽所能的恶毒。他只听从神的低语，并认为自己是人类的救世主。</p>'
                }
            ]
        },
        task103:{
            bg:gloCfg.flowPath+'task103-bg.jpg',
            dia:[
                {txt:'<p>我们正式踏入伊甸教的地盘了，还有多久能到？</p>'},
                {txt:'<p>久到能让你回心转意，这样你就能让直升机掉头回去了。</p>'},
                {txt:'<p>你是要我忽略联邦逮发出的捕令么？警长，你真是太怂了。</p>'},
                {txt:'<p>不，长官，我是要你了解现在的真实情况：约瑟夫·席德不是那种会认人宰割的家伙。我们之前曾跟他交过手几次，但不是每次都能占上风……有时候，保持现状才是最好的方式。</p>'},
                {txt:'<p>警长，国家之所以建立法律是有理由的，我也要把这理由给约瑟夫讲讲。还有，你说的“伊甸教徒”是什么意思？</p>'},
                {txt:'<p>“伊甸之门计划”就简称为“伊甸教”，这是本地人称呼他们的方式。你知道，几年前他们刚成立时是个无害的教派，但现在他们全副武装，随时想找人开战。</p>'},
                {txt:'<p>警长，你害怕也晚了，现在他们的地盘就在我们脚下。</p>'}
            ]
        },
        task104:{
            bg:gloCfg.flowPath+'task104-bg.jpg',
            tips:{
                txt:'<p>在《孤岛惊魂5》的世界里设有大量的邪教哨站，一旦邪教哨站获得解放，你就能进行新的任务与使用商店。</p><p>邪教哨站最多会设置3个警报器。如果你在解除警报前被发现，敌方增援就会被叫来。解放哨站又未被发现就会奖励更多的金钱。</p>'
            }
        },
        task105:{
            bg:gloCfg.flowPath+'task103-bg.jpg',
            dia:[
                {
                    txt:'<p>长官，真的不能返回了么。</p>'
                },
                {
                    txt:'<p>我们进去，降落吧。</p>'
                }
            ],
            transit:{
                video:{
                    player:'se',
                    vid:'jr2uy',
                    bkvid:'XMzQ4OTI1MzU4NA',
                    controls:false
                }
            }
        },
        task106:{
            bg:gloCfg.flowPath+'task106-bg.jpg',
            tro:{
                btn:gloCfg.flowPath+'task106-tro-btn.png',
                txt:gloCfg.flowPath+'task106-tro-txt.png'
            },
            arcbtn:'前往'
        },
        task107:{
            bg:gloCfg.flowPath+'task107-bg.jpg',
            tro:{
                btn:gloCfg.flowPath+'task107-tro-btn.png',
                txt:gloCfg.flowPath+'task107-tro-txt.png'
            },
            transit:{
                video:{
                    player:'se',
                    vid:'2f6sk',
                    bkvid:'XMzQ4OTI1MTgxNg',
                    controls:false
                }
            },
            arcbtn:'前往'
        },
        task108:{
            bg:gloCfg.mediaPath+'task108-vd1.mp4',
            hideTransi:{
                video:{
                    player:'se',
                    vid:'ge8qc',
                    bkvid:'XMzQ4OTI1MTU4MA',
                    controls:false
                }
            },
            hideTime:1*60*1000,
            transit:{
                video:{
                    player:'se',
                    vid:'e8yio',
                    bkvid:'XMzQ5MjAyMzM3Ng',
                    controls:false
                }
            }
        },
        task2:{
            bg:gloCfg.mediaPath+'task2-vd.mp4',
            transit:{
                video:{
                    player:'se',
                    vid:'l3s35',
                    bkvid:'XMzQ5MjAyMzE4OA',
                    controls:false
                }
            }
        },
        task201:{
            bg:gloCfg.flowPath+'task2-bg.jpg'
        },
        task202:{
            bg:gloCfg.mediaPath+'task202-vd.mp4',
            arcbtn:'迂回至障碍物后方'
        },
        task203:{
            bg:gloCfg.flowPath+'task203-bg.jpg',
            light:gloCfg.flowPath+'task203-light.png',
            arcbtn:'绕到敌人身后'
        },
        task204:{
            bg:gloCfg.mediaPath+'task204-vd.mp4',
            arcbtn:'前往'
        },
        task205:{
            bg:gloCfg.flowPath+'task205-bg.jpg',
            arr:{
                bg:gloCfg.flowPath+'task205-arr.png',
                txt:'选择绕路'
            },
            tro:'在《孤岛惊魂5》中，正面迎敌不是唯一选择，仔细观察敌我优势，制定正确的战术才是赢得胜利的关键。'
        },
        task206:{
            bg:gloCfg.flowPath+'task206-bg.jpg',
            arcbtn:'前往'
        },
        task3: {
            transit:{
                video:{
                    player:'se',
                    vid:'y6sed',
                    bkvid:'XMzQ5MjAyMzAyNA',
                    controls:false
                }
            }
        },
        task301:{
            bg:gloCfg.flowPath+'task301-bg.jpg',
            fight:{
                gun:{
                    pic:gloCfg.flowPath+'task301-gun.png',
                    fire:gloCfg.flowPath+'task301-gun-fire.png'
                },
                enemy:[
                    {
                        full:gloCfg.flowPath+'task301-enemy0.png',
                        half:gloCfg.flowPath+'task301-enemy0-r.png'
                    },
                    {
                        full:gloCfg.flowPath+'task301-enemy1.png',
                        half:gloCfg.flowPath+'task301-enemy1-r.png'
                    }
                ]
            }
        },
        task302:{
            bg:gloCfg.flowPath+'task302-bg.jpg',
            fight:{
                gun:{
                    pic:gloCfg.flowPath+'task302-gun.png',
                    fire:gloCfg.flowPath+'task302-gun-fire.png'
                },
                enemy:[
                    {
                        full:gloCfg.flowPath+'task302-enemy0.png',
                        half:gloCfg.flowPath+'task302-enemy0-r.png'
                    },
                    {
                        full:gloCfg.flowPath+'task302-enemy1.png',
                        half:gloCfg.flowPath+'task302-enemy1-r.png'
                    }
                ]
            }
        },
        task303:{
            bg:gloCfg.flowPath+'task303-bg.jpg',
            fight:{
                gun:{
                    pic:gloCfg.flowPath+'task303-gun.png',
                    fire:gloCfg.flowPath+'task303-gun-fire.png'
                },
                enemy:[
                    {
                        full:gloCfg.flowPath+'task303-enemy0.png',
                        half:gloCfg.flowPath+'task303-enemy0-r.png'
                    },
                    {
                        full:gloCfg.flowPath+'task303-enemy1.png',
                        half:gloCfg.flowPath+'task303-enemy1-r.png'
                    },
                    {
                        full:gloCfg.flowPath+'task303-enemy2.png',
                        half:gloCfg.flowPath+'task303-enemy2-r.png'
                    }
                ]
            },
            transit:{
                video:{
                    player:'se',
                    vid:'nrj5x',
                    bkvid:'XMzQ4OTI1NTY2OA',
                    controls:false
                }
            }
        },
        task304:{
            transit:{
                video:{
                    player:'se',
                    vid:'1m3gk',
                    bkvid:'XMzQ4OTI1Nzc5Ng',
                    controls:false
                }
            }
        },
        task4:{
            transit:{
                video:{
                    player:'se',
                    vid:'ut91m',
                    bkvid:'XMzQ4OTI1NTQ0MA',
                    controls:false
                }
            }
        },
        task401:{
            bg:gloCfg.flowPath+'task401-bg.jpg',
            letter:{
                icon:gloCfg.flowPath+'task401-letter.png',
                list:[
                    {
                        tit:'当地居民为用水奋战',
                        time:false,
                        con:'<p>“道奇”理查·罗斯福因为在法定集水区收集雨水而遭控告，且为此事提出辩驳，但过程中因为蔑视法庭而坐了两天牢。</p><p>“罗斯福先生在未经允许的情况下收集雨水，在蒙大拿州法律中属于相当严重的罪行。”水利局的副局长艾德温·贾西亚如此说明。</p><p>罗斯福先生将针对此指控提出辩驳。</p>',
                        name:false
                    },
                    {
                        tit:'希望郡新闻报的信',
                        time:'2014年10月13日',
                        con:'<p>亲爱的罗斯福先生。</p><p>我想和你谈谈关于最近与政府官员因为收集雨水而发生争执的事情。我这边的理解是你已经获得了许可，但却又遭到否决，导致你坐牢数日，而且还要因此不断地出庭应讯。</p><p>我想要确认你在法庭上的正式陈述，是否为“用水是上天赋予的权利”，而且“政府趁我们不注意的时候窃夺我们的资源！我们有捍卫人权和自由！”还有，你是否真的对法官说：“对，我就是在蔑视你！”了呢？</p><p>如果你想让此事公诸于世，请通知我们。</p>',
                        name:'希望郡新闻报的杰布·波依德'
                    },
                    {
                        tit:'写给道奇的信',
                        time:'2015年4月27日',
                        con:'<p>老爸，</p><p>我收到你的消息了，他们能撤销控诉真是太好了。</p><p>我们会尽可能空出一部分的暑假时间——瑞奇想让你看看他拆了辅助轮也能上路的样子——不过安妮大学那里还有不少工作要处理。</p><p>我知道这对你来说很重要，所以我们会试试看……</p><p>只不过请先别再说什么“在家上课”的事情了，好吗？这对我或安妮来说都不好，而南街的学校是最好的学习场所。我们尽量不要声张“预备末日”的作为，我知道瑞奇很喜欢，但是安妮超担心的。</p><p>见面再聊了。</p>',
                        name:'罗比'
                    }
                ]
            },
            radio:{
                icon:gloCfg.flowPath+'task401-radio.png',
                zmCfg:{
                    kf:[
                        {
                            timeStart:1,
                            timeEnd:6,
                            txt:'道奇，你在吗？我是蕾蕾。现在是什么情况？'
                        },
                        {
                            timeStart:7,
                            timeEnd:10,
                            txt:'我们听到一堆枪声，还有好几声爆炸，我敢发誓那绝对不是打雷。'
                        },
                        {
                            timeStart:11,
                            timeEnd:18,
                            txt:'阿布的情绪很激动，不肯静下来。这堆鸟事是不是又跟伊甸教徒有关啊？我们还要忍受多久？'
                        }
                    ]
                }
            }
        },
        task402:{
            bg:gloCfg.flowPath+'task402-bg.jpg'
        },
        task4021:{
            bg:gloCfg.flowPath+'task4021-bg.jpg',
            radio:{
                icon:gloCfg.flowPath+'task4021-radio.png'
            }
        },
        task4022:{
            bg:gloCfg.flowPath+'task4022-bg.jpg',
            radio:{
                zmCfg:{
                    kf:[
                        {
                            timeStart:1,
                            timeEnd:5,
                            txt:'拜托！有人在吗？邪教像军队一样地横扫这里了！'
                        },
                        {
                            timeStart:5.1,
                            timeEnd:12,
                            txt:'将人们往卡车里丢……夺走我们的食物……然后我不断听到枪声……人一个一个死去……拜托有谁可以来帮我们啊……'
                        }
                    ]
                }
            }
        },
        task403:{
            bg:gloCfg.flowPath+'task403-bg.jpg'
        },
        task4031:{
            bg:gloCfg.flowPath+'task4031-bg.jpg'
        },
        task4032:{
            bg:gloCfg.flowPath+'task4032-bg.jpg',
            transit:{
                video:{
                    player:'se',
                    vid:'o5g0w',
                    bkvid:'XMzQ4OTI1MzAwMA',
                    controls:false
                }
            },
            toast:'离开前请先与道奇交谈'
        },
        task404:{
            bg:gloCfg.flowPath+'task404-bg.jpg',
            arcbtn:'交谈',
            eye1:gloCfg.flowPath+'task404-eye-light1.png',
            eye2:gloCfg.flowPath+'task404-eye-light2.png'
        },
        task4041:{
            bg:gloCfg.flowPath+'task4041-bg.jpg',
            eyes:[
                {
                    light:gloCfg.flowPath+'task4041-eye-light0.png',
                    tit:'约瑟夫·席德(圣父)',
                    des:'<p>领导“伊甸之门”计划的“圣父”，这位圣父相信世界的崩坏迫在眉睫。他们的任务就是要拯救你的灵魂——无论你是否愿意接受救赎。</p>'
                },
                {
                    light:gloCfg.flowPath+'task4041-eye-light1.png',
                    tit:'费丝·席德（妖女）',
                    des:'<p>一旦受到费丝咒语的影响，一切就无法回头。一如约瑟夫之声，费丝以神之器的身份带来混乱，借此让教众获得祝福。</p>'
                },
                {
                    light:gloCfg.flowPath+'task4041-eye-light2.png',
                    tit:'约翰．席德（异端审判者）',
                    des:'<p>无论家庭或个人，约翰利用威吓、信仰和暴力的方式，来确保足以让这支邪教维持下去的重要资源。</p>'
                },
                {
                    light:gloCfg.flowPath+'task4041-eye-light3.png',
                    tit:'雅各．席德（战士）',
                    des:'<p>他在这支邪教中扮演招募者的角色，在从军时期也曾担任枪手的角色。席德家大哥的主要职责，在于保护“伊甸之门”计划。 </p>'
                }
            ]
        },
        task4042:{
            bg:gloCfg.flowPath+'task4042-bg.jpg',
            eye:{
                light:gloCfg.flowPath+'task4042-eye-light.png',
                name:'资料'
            }
        },
        task405:{
            bg:gloCfg.flowPath+'task405-bg.jpg',
            dia:[
                {
                    txt:'<p>刚才在那里没能好好自我介绍，大多数人叫我道奇。我探到了一点线索，你的搭档还活着……但那只是暂时的，他们好像分头行动了，一个个分别被带去见约瑟夫不同的“家人”。</p>'
                },
                {
                    txt:'<p>你想要把他们救回来，这我了解，我自己也有朋友被抓。问题是接下来不会有援兵，也没人知道这里的情况，就算知道也来不及了。外头一定还有人愿意起来对抗邪教，只要我们能让他们群起效尤就行了， 所以我们需要组织一支反抗势力。</p>'
                },
                {
                    txt:'<p>首要之事就是夺得这座岛的控制权，一旦我们有空间可以喘口气，就能想出下一步该怎么办了。</p>'
                }
            ],
            choose:{
                txt:'<p>你还想知道哪些情报？</p>',
                cse1:'反抗势力',
                cse2:'雇佣兵'
            }
        },
        task4051:{
            bg:gloCfg.flowPath+'task4051-bg.jpg'
        },
        task4052:{
            bg:gloCfg.flowPath+'task4052-bg.jpg'
        },
        task:{
            bg:gloCfg.flowPath+'task1-bg.jpg'
        }
    }
};
//预加载图片
 var preLoadPicsLists = {
     list1: [
         pageConfig.pages.pgStart.slogan
     ]
 };