var gsdsPath1 = '//img7.gamersky.com/zqimg/dgy/godofwar4/',gsdsPath2 = '//img7.gamersky.com/zqimg/dgy/godofwar4/',gsDgySource;
gsDgySource = {
    bgm:{
        start:gsdsPath1+'ztmedia/bgm.mp3'
    },
    page:{
        gsdCommon:{
            slogan:gsdsPath1+'ztimages/slogan.png'
        },
        gsdLoad:{
            logo1:gsdsPath1+'ztimages/ld-logo.png',
            logo2:gsdsPath1+'ztimages/ld-logo-g.png'
        },
        gsdStart:{
            bg:gsdsPath1+'ztimages/gsdStart.jpg',
            vd:gsdsPath1+'ztmedia/bg-start.mp4'
        },
        gsdEnd:{
            bg:gsdsPath1+'ztimages/gsdEnd.jpg',
            vd:gsdsPath1+'ztmedia/bg-end.mp4',
            maker:{
                con:'<h5>内容策划</h5><p>FoxJR、短笛酱</p><h5>视觉设计</h5><p>Drakedooog、MrrrTian</p>'
            }
        },
        gsdBuy:{
            bg:gsdsPath1+'ztimages/gsdEnd.jpg',
            vd:gsdsPath2+'ztmedia/bg-buy.mp4',
            logo:gsdsPath1+'ztimages/buy-logo.png',
            role:{
                b:gsdsPath1+'ztimages/buy-role-b.png',
                s:gsdsPath1+'ztimages/buy-role-s.png'
            },
            sld:[
                {
                    tit:'数字标准版',
                    pic:gsdsPath1+'ztimages/ver0.png',
                    big:gsdsPath1+'ztimages/ver0b.png',
                    url:'https://store.playstation.com/zh-hant-hk/product/HP9000-CUSA07413_00-00000000GODOFWAR'
                },
                {
                    tit:'收藏版',
                    pic:gsdsPath1+'ztimages/ver1.png',
                    big:gsdsPath1+'ztimages/ver1b.png',
                    url:'https://www.amazon.com/God-War-Collectors-PlayStation-4/dp/B0797CKXC4/ref=sr_1_3?s=videogames&ie=UTF8&qid=1524130739&sr=1-3&keywords=god+of+war'
                },
                {
                    tit:'石匠限定版',
                    pic:gsdsPath1+'ztimages/ver2.png',
                    big:gsdsPath1+'ztimages/ver2b.png',
                    url:'https://www.amazon.com/God-War-Stone-Masons-PlayStation-4/dp/B0792SPV9J/ref=sr_1_2?s=videogames&ie=UTF8&qid=1524126534&sr=1-2&keywords=god+of+war'
                },
                {
                    tit:'数字豪华版',
                    pic:gsdsPath1+'ztimages/ver3.png',
                    big:gsdsPath1+'ztimages/ver3b.png',
                    url:'https://store.playstation.com/zh-hant-hk/product/HP9000-CUSA07413_00-GODOFWARDDE00000'
                }
            ]
        },
        gsdStory:{
            vd:'XMzU1MDA1NTA3Mg'
        }
    },
    flow:{
        gsdFlow01:{
            vd:gsdsPath1+'ztmedia/flow/flow01.mp4'
        },
        gsdFlow02:{
            vd1:gsdsPath2+'ztmedia/flow/flow02.mp4',
            vd2:gsdsPath1+'ztmedia/flow/flow02loop.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'r',
                    showTime:35.2,
                    txt:'按<span>R</span>键砍树'
                }
            ]
        },
        gsdFlow03:{
            vd1:gsdsPath2+'ztmedia/flow/flow03.mp4',
            vd2:gsdsPath1+'ztmedia/flow/flow03loop.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'r',
                    showTime:4,
                    txt:'按<span>R</span>键砍树'
                }
            ]
        },
        gsdFlow04:{
            vd1:gsdsPath1+'ztmedia/flow/flow041.mp4',
            vd2:gsdsPath1+'ztmedia/flow/flow042loop.mp4',
            vd3:gsdsPath2+'ztmedia/flow/flow043.mp4',
            vd4:gsdsPath2+'ztmedia/flow/flow044loop.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'w',
                    showTime:85,
                    txt:'按住<span>W</span>前进'
                },
                {
                    tid:1,
                    downKey:'r',
                    showTime:10,
                    txt:'按<span>R</span>上船'
                }
            ]
        },
        gsdFlow05:{
            vd1:gsdsPath1+'ztmedia/flow/flow051.mp4',
            vd2:gsdsPath1+'ztmedia/flow/flow052loop.mp4',
            vd3:gsdsPath2+'ztmedia/flow/flow053.mp4',
            vd4:gsdsPath2+'ztmedia/flow/flow054loop.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'w',
                    showTime:37,
                    txt:'按住<span>W</span>前进'
                },
                {
                    tid:1,
                    downKey:'r',
                    showTime:27,
                    txt:'按<span>R</span>下船'
                }
            ]
        },
        gsdFlow06:{
            vd1:gsdsPath1+'ztmedia/flow/flow061.mp4',
            vd2:gsdsPath1+'ztmedia/flow/flow062loop.mp4',
            vd3:gsdsPath2+'ztmedia/flow/flow063.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'w',
                    showTime:34,
                    txt:'按住<span>W</span>前进'
                }
            ]
        },
        gsdFlow07:{
            vd1:gsdsPath1+'ztmedia/flow/flow071.mp4',
            vd2:gsdsPath1+'ztmedia/flow/flow072loop.mp4',
            vd3:gsdsPath2+'ztmedia/flow/flow073.mp4',
            vd4:gsdsPath2+'ztmedia/flow/flow074loop.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'w',
                    showTime:281.8,
                    txt:'按住<span>W</span>前进'
                },
                {
                    tid:1,
                    downKey:'r',
                    showTime:37.3,
                    txt:'按下<span>R</span>跳过裂隙'
                }
            ]
        },
        gsdFlow08:{
            vd1:gsdsPath1+'ztmedia/flow/flow08.mp4',
            vd2:gsdsPath2+'ztmedia/flow/flow08loop.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'r',
                    showTime:14.1,
                    txt:'按<span>R</span>跳跃物体'
                }
            ]
        },
        gsdFlow09:{
            vd1:gsdsPath2+'ztmedia/flow/flow09.mp4',
            vd2:gsdsPath1+'ztmedia/flow/flow09loop.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'e',
                    showTime:28,
                    txt:'按下<span>E</span>装备利维坦之斧子'
                }
            ]
        },
        gsdFlow10:{
            vd1:gsdsPath1+'ztmedia/flow/flow10.mp4',
            vd2:gsdsPath2+'ztmedia/flow/flow10loop.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'q',
                    showTime:0.3,
                    txt:'按<span>Q</span>以瞄准'
                }
            ]
        },
        gsdFlow11:{
            vd1:gsdsPath2+'ztmedia/flow/flow11.mp4',
            vd2:gsdsPath1+'ztmedia/flow/flow11loop.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'t',
                    showTime:0.2,
                    txt:'按下<span>T</span>抛出斧头'
                }
            ]
        },
        gsdFlow12:{
            vd1:gsdsPath1+'ztmedia/flow/flow12.mp4',
            vd2:gsdsPath2+'ztmedia/flow/flow12loop.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'b',
                    showTime:5.3,
                    txt:'按下<span>B</span>召回斧头'
                }
            ]
        },
        gsdFlow13:{
            vd1:gsdsPath2+'ztmedia/flow/flow13.mp4',
            vd2:gsdsPath1+'ztmedia/flow/flow13loop.mp4',
            tips:[
                {
                    tid:0,
                    downKey:'r',
                    showTime:10,
                    txt:'按下<span>R</span>跳过裂隙'
                }
            ]
        },
        gsdFlow14:{
            vd:gsdsPath1+'ztmedia/flow/flow14.mp4'
        }
    }
};