var pageConfig = {
    countid:'1007384',
    bgm:{
        txt:['打开声音','关闭声音'],
        start:'http://image.gamersky.com/zqimg/mhw/pc/bgm.mp3',
        hunt:'http://image.gamersky.com/zqimg/mhw/pc/bgm-hunt.mp3'
    },
    userMute:true,
    volClk:true,
    isFixedNav:true,
    isHb:true,
    isCommOpen:false,
    isVideoPlaying:false,
    addedComment:false,
    bgmvol:1,
    imglist:{
        loading:{
            logo1:'http://image.gamersky.com/zqimg/mhw/pc/ld-logo.png',
            logo2:'http://image.gamersky.com/zqimg/mhw/pc/ld-logo-g.png'
        },
        ldPage:{
            vd:'http://image.gamersky.com/zqimg/mhw/pc/vd-start.mp4'
        },
        begin:{
            bg:'http://image.gamersky.com/zqimg/mhw/pc/bg_begin.jpg',
            gs:'http://www.gamersky.com/zl/preview/',
            txt:'<p>每隔10年，古龙们就会以遥远的新大陆为目标渡过大海，这种现象被称为“古龙渡”。</p>\n' +
            '<p>为了调查这一奇妙的现象，公会成立了“新大陆古龙调查团”，多次派遣调查团前往新大陆。</p>\n' +
            '<p>然而，今次已是第五次派遣，追踪正在渡海的古龙灭尽龙后方，在这巨大的船中，可以见到猎人的姿态……</p>'
        },
        end:{
            bg:'http://image.gamersky.com/zqimg/mhw/pc/bg_end.jpg',
            para:'<p><b>专题策划：</b>观海、天增弟弟、Mirror明镜</p><p><b>视觉设计：</b>Drakedooog、MrrrTian</p>'
        },
        comm:{
            bg:'http://image.gamersky.com/zqimg/mhw/pc/bg_comm.jpg'
        },
        pgGamerVer:{
            bg:'http://image.gamersky.com/zqimg/mhw/pc/bg_gmvr.jpg',
            des:'请购买游戏，获得完整狩猎体验！',
            list:[
                {
                    tit:'标准版',
                    buy:'https://store.playstation.com/#!/zh-hant-hk/%e9%81%8a%e6%88%b2/monster-hunter-world-pre-order/cid=HP0102-CUSA09554_00-ASIAPLACEHOLDER0',
                    pic:'http://image.gamersky.com/zqimg/mhw/pc/gmvr1.png',
                    lis:['<p>《怪物猎人：世界》游戏本体</p>']
                },
                {
                    tit:'豪华版',
                    buy:'https://store.playstation.com/#!/zh-hant-hk/%e9%81%8a%e6%88%b2/monster-hunter-world-digital-deluxe-edition-pre-order/cid=HP0102-CUSA09554_00-ASIAPLACEHOLDER1',
                    pic:'http://image.gamersky.com/zqimg/mhw/pc/gmvr2.png',
                    lis:['<p>《怪物猎人：世界》游戏本体</p>','<p>豪华组合<span>外观装备 「铠武者系列」</span><span>3种追加手势「正坐」「投射飞镖」「强推」</span><span>2种追加奖章套件「MH歴代角色人物套件」「全熟肉吉祥物套件」</span><span>追加涂鸭 「龙」</span><span>追加髮型 「冲天炮」</span></p>']
                },
                {
                    tit:'典藏版',
                    buy:'https://www.gamestop.com/browse?nav=16k-Monster+Hunter+World',
                    pic:'http://image.gamersky.com/zqimg/mhw/pc/gmvr3.png',
                    lis:['<p>《怪物猎人：世界》游戏本体</p>','<p>豪华组合<span>外观装备 「铠武者系列」</span><span>3种追加手势「正坐」「投射飞镖」「强推」</span><span>2种追加奖章套件「MH歴代角色人物套件」「全熟肉吉祥物套件」</span><span>追加涂鸭 「龙」</span><span>追加髮型 「冲天炮」</span></p>','<p>原装模型<span>(尺寸: 约W 140mm x D 170mm x H 125mm)</span></p>','<p>《怪物猎人：世界》特别原声<span>(10 首)</span></p>','<p>《怪物猎人：世界》画册「Monster Designs」<span>(尺寸: W 216mm x H 279mm, 32页精装版)</span></p>']
                }
            ]
        },
        pgStarBase:{
            bg:'http://image.gamersky.com/zqimg/mhw/pc/bg_starbase.jpg',
            intro:{
                tit:'星辰',
                des:'<p>生活在新大陆所有调查员的「家」——调查据点亚斯提拉（アステラ）。</p><p>可以说是生活在新大陆所有调查员的「家」。负责调查的研究区域；支撑调查行动的物流、工房区域；猎人们匯集的集会区域等等，有许多不同的区域。在四十年前由第一期调查队建立，并经过长年修改，才成为现在这个模样。</p>'
            }
        },
        pgMeeting:{
            bg:'http://image.gamersky.com/zqimg/mhw/pc/bg_meeting.jpg',
            box:'http://image.gamersky.com/zqimg/mhw/pc/meeting-box.png',
            intro:{
                tit:'集会区域',
                des:'<p>每个聚会区域最多容纳16人同时聚集。</p><p>你可以和来自世界各地的玩家组成最多4人的队伍展开游戏。</p><p>在这儿不但可以共同出发执行任务，甚至还能相互比拼腕力。</p>'
            }
        },
        pgMyself:{
            bg:'http://image.gamersky.com/zqimg/mhw/pc/bg_myself.jpg',
            intro:{
                tit:'自己的房间',
                des:'<p>在自己的房间中有玩家熟悉的道具箱、随行猫管理等功能。此外，玩家可以在自己的房间中饲养从新大陆捕捉的各种环境生物，随着游戏的进行，房间的类型和等级还会有所变化，房间功能将逐渐扩展开来，可以放入房间中的环境生物数量和种类也有所不同。</p>'
            },
            rabbit:'http://image.gamersky.com/zqimg/mhw/pc/rabbit-txt.png',
            box:'http://image.gamersky.com/zqimg/mhw/pc/myself-box.png',
            cat:{
                txt:'http://image.gamersky.com/zqimg/mhw/pc/myself-cat-txt.png',
                role:'http://image.gamersky.com/zqimg/mhw/pc/myself-cat.png',
                video:'XMzM4NTY5NjA2NA'
            }
        },
        pgWorking:{
            bg:'http://image.gamersky.com/zqimg/mhw/pc/bg_working.jpg',
            intro:{
                tit:'加工屋',
                des:'<p>与装备有关的机能都能一手包办的工房。</p><p>对于前往进行严苛调查的猎人来说，是非常重要的设施。</p><p>负责武器和防具的强化、生产，甚至把一部分武器的强化返回原来的样子。</p>'
            },
            dia:'http://image.gamersky.com/zqimg/mhw/pc/working-dia.png'
        },
        pgMonster:{
            bg:'http://image.gamersky.com/zqimg/mhw/pc/bg_monster.jpg',
            intro:{
                tit:'加工屋',
                des:'<p>与装备有关的机能都能一手包办的工房。</p><p>对于前往进行严苛调查的猎人来说，是非常重要的设施。</p><p>负责武器和防具的强化、生产，甚至把一部分武器的强化返回原来的样子。</p>'
            },
            dia:'http://image.gamersky.com/zqimg/mhw/pc/working-dia.png'
        },
        pgMap:{
            bg:'http://image.gamersky.com/zqimg/mhw/pc/bg_map.jpg',
            intro:{
                tit:'简介',
                des:'<p>《怪物猎人：世界》的大地图是无缝衔接的，在这个世界中，有多个环境迥异的猎场，目前已知的可探索区域包括古树森林、大蚁塚荒地、陆珊瑚台地和瘴气之谷。</p><p>玩家可以从世界地图中前往不同猎场进行探索狩猎，你将感受到一个充满生机与自由的世界。</p><p>当然，你也可以利用它返回星辰据点。</p>'
            }
        },
        pgHunt:{
            bg:'http://image.gamersky.com/zqimg/mhw/pc/bg_hunt.jpg',
            btns:{
                btn1:'http://image.gamersky.com/zqimg/mhw/pc/hunt-intro.png',
                btn2:[
                    {tit:'准备狩猎',des:'为你所要面对的任务做好充足准备，仔细考虑最适合的装备、技能、猫侍和手上拥有的武器元素。你可以在营地改变自己的装备。'},
                    {tit:'怪物部分',des:'在怪物们的身上有些柔软的地方难以抵挡攻击，不过也有相对更坚韧、更耐用的部位。识别怪物的弱点是成为一个成功猎人的关键。'},
                    {tit:'元素属性',des:'游戏中存在五种元素属性：火、雷、水、冰和龙，利用怪物的元素弱点可对其造成额外伤害。'},
                    {tit:'怪物',des:'你可以通过在半空中的攻击来骑在怪兽身上。一旦骑怪兽成功，如果你在继续攻击的过程中没有被怪兽挣脱甩开，那么你就可以把它击倒。'},
                    {tit:'骑乘控制',des:'一旦你骑在一只怪物身上，当怪物疯狂挣扎的时候你要按下R2来让自己紧抓住不放手，或者按L来使自己避开某些攻击。请小心：如果你的体力消耗完，你就会自动从它身上脱落。'},
                    {tit:'了解你的环境',des:'在不同的环境中有五花八门的特殊动物和有趣的点来帮助你狩猎，你可以通过地图来查看它们是什么以及它们在哪里。'},
                    {tit:'怪物冲突',des:'当大型怪物相遇时，它们可能会相互攻击，利用好这样的情况将狩猎变成你的最爱。'},
                    {tit:'打破怪物的身体部位',des:'把你的攻击集中在怪物特定的身体部位可能会破坏它们，从而削弱怪物，有时还能限制其移动性或攻击。另外，还有一些材料只能通过打破怪物身体的某些部分获得。'},
                    {tit:'利用环境',des:'仔细观察你周围的环境，在你的身旁充满了可以跳下的平台、可以爬的墙壁以及可以滑下的斜坡。'},
                    {tit:'楔形甲虫',des:'楔形甲虫可以在许多不同的地方找到，将你的瞄准固定在一个点上，然后按下O钩住它，便可以摆荡穿行。'},
                    {tit:'盔甲技能',des:'盔甲中充满了各种技能，能为你带来积极的效果，并提高你的人物属性。选择最能符合你所使用的武器或游戏风格的盔甲技能。'},
                    {tit:'镜头类型',des:'你可以在选项中选择镜头类型。<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;聚焦：始终固定在目标上。<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;目标：按下按钮时固定在目标身上。'},
                    {tit:'镜头设置',des:'你可以从开始菜单更改各种镜头设置。'},
                    {tit:'快速旅行',des:'你可以从野生动物地图中快速回到营地，不过要小心：在战斗中或当怪物已经警惕到你的存在时，你无法使用这项功能。'}
                ]
            },
            video:{
                vd1:'http://image.gamersky.com/zqimg/mhw/pc/hunt-vd1.mp4',
                vd1Keys:[
                    {
                        time:5,
                        key:'g',
                        tips:{
                            keyshow:'按<i>G</i>穿上隐形衣装',
                            pop:{
                                tit:'隐形衣装',
                                des:'<p>一定时间内从怪物的视线中隐藏身影。进行攻击或受到伤害时，效果就会结束。</p>'
                            }
                        }
                    },
                    {
                        time:18,
                        key:'x',
                        tips:{
                            keyshow:'按<i>X</i>攻击'
                        }
                    },
                    {
                        time:28,
                        key:'f',
                        tips:{
                            keyshow:'按<i>F</i>踢翻麻痹蟾蜍',
                            pop:{
                                tit:'麻痹蟾蜍',
                                des:'<p>它们体型较胖，拥有黄色的伪装，当你踢爆它们时，它们会放出麻痹气体，令怪物麻痹，也能让猎人麻痹。</p>'
                            }
                        }
                    },
                    {
                        time:32.7,
                        key:'x',
                        tips:{
                            keyshow:'按<i>X</i>跳到灭尽龙背上'
                        }
                    },
                    {
                        time:38,
                        key:'x',
                        tips:{
                            keyshow:'按<i>X</i>连续攻击'
                        }
                    },
                    {
                        time:39,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:40,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:41,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:42,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:43,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:44,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:45,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:46,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:47,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:48,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:49,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:50,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    },
                    {
                        time:51,
                        key:'x',
                        tips:{
                            keyshow:'猛按<i>X</i>攻击'
                        }
                    }
                ],
                vd2:'XMzM4NTY2MjE1Mg',
                vd3:'http://image.gamersky.com/zqimg/mhw/pc/hunt-vd3.mp4',
                vd3loop:'http://image.gamersky.com/zqimg/mhw/pc/hunt-vd3-loop.mp4',
                vd3Keys:[
                    {
                        time:0,
                        key:'e',
                        tips:{
                            keyshow:'按<i>E</i>继续',
                            pop:{
                                tit:'导虫',
                                des:'<p>怪兽的足印和爪痕等踪迹遍布在四周，你的导虫会记得怪兽的气味并带领你寻找它们。当你搜集得到越多踪迹，导虫便能为你带来越多的资讯。</p>'
                            }
                        }
                    },
                    {
                        time:7.3,
                        key:'g',
                        tips:{
                            keyshow:'按<i>G</i>换上滑翔衣装',
                            pop:{
                                tit:'滑翔衣装',
                                des:'<p>跳跃时空中停留的时间变得较长，在有强风吹的地方使用</p>'
                            }
                        }
                    },
                    {
                        time:9.4,
                        key:'f',
                        tips:{
                            keyshow:'按<i>F</i>滑翔'
                        }
                    },
                    {
                        time:19.8,
                        key:'e',
                        tips:{
                            keyshow:'按<i>E</i>继续',
                            pop:{
                                tit:'利用火药桶击杀灭尽龙',
                                des:'<p>小炸药桶定时引爆，大桶需要主动引爆。引爆方法：1、用小炸药桶引爆。2、各种飞刀。3、弓、各种弩。4、用武器砍或用脚踢爆。</p>'
                            }
                        }
                    }
                ],
                vd4:'XMzM4NzYzNjgwNA',
                vd5:'http://image.gamersky.com/zqimg/mhw/pc/hunt-vd5.mp4'
            }
        },
        hd:{
            monster:{
                name:'魔物',
                con:[
                    {
                        group:'mp1',
                        hunted:false,
                        tit:'贼龙',
                        des:'<p>是率领凶豺龙群族的领导。</p><p>食欲旺盛，在空腹的时候会变得很暴躁。</p><p>整个吞下捕杀的猎物的模样是最精彩的部分</p>',
                        vd:'XMzM4MTIxMTk4OA',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp1-zl.png'
                    },
                    {
                        group:'mp1',
                        hunted:false,
                        tit:'吐毒龙',
                        des:'<p>体内有毒液的鸟龙种。</p><p>会吞吃飞散核桃之类的植物蓄积在嘴里或尾巴，再混合毒液喷出强力的剧毒吐息。</p>',
                        vd:'XMzM4MTIwOTEyOA',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp1-tdl.png'
                    },
                    {
                        group:'mp1',
                        hunted:false,
                        tit:'飞雷龙',
                        des:'<p>栖息在树上，在林木间飞舞活动的牙龙种。</p><p>似乎会藉由移动时摩擦林木与地面，使体毛能够蓄积静电。</p>',
                        vd:'XMzM4MDk4NjkzMg',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp1-fll.png'
                    },
                    {
                        group:'mp1',
                        hunted:false,
                        tit:'蛮颚龙',
                        des:'<p>对这个捕食对象丰富的森林虎视眈眈。</p><p>非常好战的他对其它魔物是毫不犹豫地袭击。</p>',
                        vd:'XMzM4MDk4Njk0MA',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp1-mel.png'
                    },
                    {
                        group:'mp1',
                        hunted:false,
                        tit:'火龙',
                        des:'<p>整个古树森林生态系统最顶尖的魔物。</p><p>可怕的飞龙会利用锐利的毒爪和火暖燥的呼吸降落在入侵者身上。</p>',
                        vd:'XMzM4MDk4NjkzNg',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp1-xhl.png'
                    },
                    {
                        group:'mp2',
                        hunted:false,
                        tit:'搔鸟',
                        des:'<p>这种怪物擅于以它们有力的前脚抓住物件。</p><p>因此可于「大蚁塚荒地」和「古树森林」内偷盗怪物蛋。</p><p>它们亦擅于抓住大石并置于身前以保护自己。</p>',
                        vd:'XMzM4MDk4NjM3Mg',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp2-sn.png'
                    },
                    {
                        group:'mp2',
                        hunted:false,
                        tit:'土砂龙',
                        des:'<p>这种怪物经常一边漫步一边寻找蚂蚁，它会用泥浆标记自己的领地。</p><p>一旦它们的领地受到侵犯，就会迅速地攻击破坏者。</p><p>它们以泥浆保护自己，亦会将泥浆洒落别人身上作攻击。</p>',
                        vd:'XMzM4MDk4NjM2OA',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp2-tsl.png'
                    },
                    {
                        group:'mp2',
                        hunted:false,
                        tit:'泥鱼龙',
                        des:'<p>于「大蚁塚荒地」沼泽区中居住的大型鱼龙。</p><p>会利用泥浆捉拿猎物、保护自己，有时会对入侵其领地的怪物进行攻击。</p>',
                        vd:'XMzM4MDk4NTgzNg',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp2-nyl.png'
                    },
                    {
                        group:'mp2',
                        hunted:false,
                        tit:'雌火龙',
                        des:'<p>主要在地上进行狩猎，别称为“陆之女王”。</p><p>曾被目击到火龙成双成对进行狩猎的案例。它会运用优秀的脚力和含毒液的尾巴收拾猎物。</p>',
                        vd:'XMzM4MDk4NTgzMg',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp2-chl.png'
                    },
                    {
                        group:'mp2',
                        hunted:false,
                        tit:'角龙',
                        des:'<p>大蚁冢荒地之主。</p><p>有着强烈的领土意识以及暴君般的攻击性。</p><p>还有着把地面上发出大声响的猎物拉进地下领土的习性。</p>',
                        vd:'XMzM4MDk4NTg0MA',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp2-jl.png'
                    },
                    {
                        role:'enter',
                        group:'mp2',
                        hunted:false,
                        tit:'灭尽龙',
                        des:'<p>灭尽龙是一只古龙种，古龙种便是威胁性大的代名词，同时也表明了它对麻痹陷阱免疫，不过武器的异常属性例如麻痹锤还是有用的，麻痹飞刀、毒飞刀和异常子弹都将变得非常有用。</p>',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp2-mjl.jpg',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp2-mjl.png'
                    },
                    {
                        group:'mp3',
                        hunted:false,
                        tit:'眩鸟',
                        des:'<p>一发现猎物或天敌，发光器官就会张大发出耀眼的闪光制造破绽。</p><p>会活用脚力发动攻击解决猎物。</p>',
                        vd:'XMzM4MTIxMTExMg',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp3-xn.png'
                    },
                    {
                        group:'mp3',
                        hunted:false,
                        tit:'浮空龙',
                        des:'<p>以陆珊瑚的卵为主要食物的飞龙种。</p><p>能在体内蓄积空气，再喷出气流进行空中移动，同时还会利用坚硬的尾巴施展强力攻击。</p>',
                        vd:'XMzM4MTIxMDg2MA',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp3-fkl.png'
                    },
                    {
                        group:'mp3',
                        hunted:false,
                        tit:'风漂龙',
                        des:'<p>以芳翼龙群为捕食对象，在狙击猎物时会全身放出冷气，令其行动迟缓后进行狩猎。</p>',
                        vd:'XMzM4MTIxMTU0NA',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp3-fpl.png'
                    },
                    {
                        group:'mp4',
                        hunted:false,
                        tit:'痹贼龙',
                        des:'<p>受到陆珊瑚台地掉下的怪物尸肉所吸引而在瘴气谷中徘徊的怪物，在狩猎时会运用它有着麻痹毒性的大牙。</p>',
                        vd:'XMzE0Nzc2OTY0OA',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp4-bzl.png'
                    },
                    {
                        group:'mp4',
                        hunted:false,
                        tit:'骨锤龙',
                        des:'<p>以瘴气谷中的怪物尸体为食的兽龙种，尸骨缠绕其全身。</p><p>有人曾目击到它会把身体蜷曲起来，通过转动身体快速移动或是进行攻击。</p>',
                        vd:'XMzE0Nzc4NDA0OA',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp4-gcl.png'
                    },
                    {
                        group:'mp4',
                        hunted:false,
                        tit:'惨爪龙',
                        des:'<p>在瘴气谷中徘徊寻觅尸体的可怖怪物。</p><p>它具有非常强的攻击性，不论是人或是怪物都可能成为它的一顿美餐。</p>',
                        vd:'XMzE0Nzg4ODIwNA',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mp4-czl.png'
                    },
                    {
                        group:'mpother',
                        hunted:false,
                        tit:'炎王龙',
                        des:'<p>火炎缠身的凶暴古龙，能够喷吐灼热的吐息。</p><p>脾气凶暴，敢于正面跟它对峙的人无一例外都会葬身火海。</p>',
                        vd:'XMzM4MTIxMjY0NA'
                    },
                    {
                        group:'mpother',
                        hunted:false,
                        tit:'钢龙',
                        des:'<p>能够呼唤风暴，不让任何人接近自己身边的古龙。</p><p>拥有相当硬的金属质地外壳覆盖全身。</p>',
                        vd:'XMzM4MTIxMjYzNg'
                    },
                    {
                        group:'mpother',
                        hunted:false,
                        tit:'岩贼龙',
                        des:'<p>以岩石为主食的怪物。通过混合唾液的成份，把具爆炸性的岩石储存于口内，然后吐出，用作防范天敌保护自己。</p>',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/monster/mpother-yzl.png'
                    }
                ]
            },
            map:{
                name:'地图',
                con:[
                    {
                        group:'mp1',
                        gone:false,
                        tit:'古树森林',
                        des:'<p>一排排地生长的古树串联成为一片广阔的「古树森林」，高耸入云。这些古树形成一个生态系统，涵盖着森林内所有生物。</p>',
                        fulldes:'<p>一排排地生长的古树串联成为一片广阔的「古树森林」，高耸入云。</p><p>这些古树形成一个生态系统，涵盖着森林内所有生物。</p>',
                        vd:'XMzM4MDk5MTkxMg',
                        pic:''
                    },
                    {
                        group:'mp2',
                        gone:false,
                        tit:'大蚁塚荒地',
                        des:'<p>这片荒地有着广大的干旱地区，但也有着生长繁盛古树的沼泽水源。大量的大蚁冢遍布整个沙地，水域中则生长着各种颜色鲜艳的植物。</p>',
                        fulldes:'<p>这片荒地有着广大的干旱地区，但也有着生长繁盛古树的沼泽水源。</p><p>大量的大蚁冢遍布整个沙地，水域中则生长着各种颜色鲜艳的植物。</p><p>这片荒地有着截然不同的两面生态，许多生物也都适应了环境生活于此。</p>',
                        vd:'XMzM4MDk4NjM3Ng',
                        pic:''
                    },
                    {
                        group:'mp3',
                        gone:false,
                        tit:'陆珊瑚台地',
                        des:'<p>既似陆又似海、高低差巨大的高原，出产陆珊瑚之卵，卵会随着涌升流随风飘出高原、散播向新大陆的其他区域，也成了某些生物的主要食物来源。</p>',
                        fulldes:'<p>既似陆又似海、高低差巨大的高原，拥有着丰富到不可思议的生态系统。</p><p>出产陆珊瑚之卵，卵会随着涌升流随风飘出高原、散播向新大陆的其他区域，也成了某些生物的主要食物来源。</p>',
                        vd:'XMzM4MTI0Mjk1Ng',
                        pic:''
                    },
                    {
                        group:'mp4',
                        tit:'瘴气之谷',
                        gone:false,
                        des:'<p>瘴气谷位于陆珊瑚台地的下方。腐烂的怪物骨头与血肉形成了一层特殊的地表，这里四处飘散的以有机物为食的细菌群，它们就是“瘴气”的真面目。</p>',
                        fulldes:'<p>瘴气谷位于陆珊瑚台地的下方。</p><p>台地上怪物的尸体坠入这片山谷，腐烂的怪物骨头与血肉形成了一层特殊的地表，而这似乎也是瘴气谷生态的重要一环。</p><p>瘴气谷最独特的地方也就在于四处飘散的以有机物为食的细菌群，它们就是“瘴气”的真面目。</p>',
                        vd:'XMzE0Nzc1NDk5Mg',
                        pic:''
                    }
                ]
            },
            other:{
                name:'基地',
                con:[
                    {
                        tit:'星辰',
                        des:'<p>可以说是生活在新大陆所有调查员的「家」。负责调查的研究区域；支撑调查行动的物流、工房区域；猎人们匯集的集会区域等等，有许多不同的区域。在四十年前由第一期调查队建立，并经过长年修改，才成为现在这个模样。</p>',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/other-xc.jpg'
                    },
                    {
                        tit:'集会区域',
                        des:'<p>每个聚会区域最多容纳16人同时聚集。你可以和来自世界各地的玩家组成最多4人的队伍展开游戏。在这儿不但可以共同出发执行任务，甚至还能相互比拼腕力。</p>',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/other-jh.jpg'
                    },
                    {
                        tit:'加工屋',
                        des:'<p>与装备有关的机能都能一手包办的工房。对于前往进行严苛调查的猎人来说，是非常重要的设施。负责武器和防具的强化、生产，甚至把一部分武器的强化返回原来的样子。</p>',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/other-jg.jpg'
                    },
                    {
                        tit:'自己的房间',
                        des:'<p>在自己的房间中有玩家熟悉的道具箱、随行猫管理等功能。此外，玩家可以在自己的房间中饲养从新大陆捕捉的各种环境生物，随着游戏的进行，房间的类型和等级还会有所变化，房间功能将逐渐扩展开来，可以放入房间中的环境生物数量和种类也有所不同。</p>',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/other-self.jpg'
                    }
                ]
            },
            weapon:{
                name:'武器',
                con:[
                    {
                        tit:'操虫棍 ',
                        des:'<p>可从空中开始发动立体攻击，能够操纵猎虫，采取提炼物来强化自己。</p>',
                        vd:'XMzM4Nzc0OTIwNA',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp01.png'
                    },
                    {
                        tit:'盾斧',
                        des:'<p>拥有高机动性的利剑和威力大的斧两种武器模式，消耗累计在药瓶的能量可提高火力。</p>',
                        vd:'XMzM4Nzc0OTIwMA',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp02.png'
                    },
                    {
                        tit:'铳枪',
                        des:'<p>附加了炮击功能的攻击武器，其魅力是各种各样的炮击系动作。</p>',
                        vd:'XMzM4Nzc0OTE5Ng',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp03.png'
                    },
                    {
                        tit:'大锤',
                        des:'<p>结合破坏力和机动性的重击武器，以攻击头部让怪物昏厥为目标，蓄力的一击很强大。</p>',
                        vd:'XMzM4Nzc0OTg1Ng',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp04.png'
                    },
                    {
                        tit:'大剑',
                        des:'<p>挥动和移动虽然缓慢，但攻击力却很高；“蓄能斩”拥有全部武器中最高级别的威力。</p>',
                        vd:'XMzM4Nzc0OTg2MA',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp05.png'
                    },
                    {
                        tit:'弓',
                        des:'<p>可以蓄力，进行各种射击的中距离武器。填装各种药瓶在箭矢上，可发挥丰富的特殊效果。</p>',
                        vd:'XMzM4Nzc0OTg2NA',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp06.png'
                    },
                    {
                        tit:'片手剑',
                        des:'<p>特点是灵活与无间隙的攻击，拔刀时也可以使用物品，适合狩猎时使用各种各样的物品。</p>',
                        vd:'XMzM4Nzc1MDI4NA',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp07.png'
                    },
                    {
                        tit:'轻弩',
                        des:'<p>以快速射击和回避为特色的远距离武器，可使用特殊状态系列的子弹（如起爆龙弹），善于支援全体成员。</p>',
                        vd:'XMzM4Nzc1MDI5Ng',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp08.png'
                    },
                    {
                        tit:'狩猎笛',
                        des:'<p>长距离，易于操作的重击武器，演奏的话，可以给自己和队友带来各种各样的效果。</p>',
                        vd:'XMzM4Nzc1MDMwMA',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp09.png'
                    },
                    {
                        tit:'双剑',
                        des:'<p>擅长于怒涛般的连续攻击，“鬼人化”虽消耗体力却容许进一步发动连续攻击。</p>',
                        vd:'XMzM4Nzc1MDkxMg',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp10.png'
                    },
                    {
                        tit:'太刀',
                        des:'<p>轻盈的动作、连续攻击是其魅力所在，可利用“气刃斩”提高攻击力。</p>',
                        vd:'XMzM4Nzc1MDk0NA',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp11.png'
                    },
                    {
                        tit:'斩击斧',
                        des:'<p>以斧和剑两种模式行动的武器，剑模式的“属性解放突刺”很强大。用接触距离长的“斧模式”来牵制，用攻击速度快的“剑模式”来猛攻。</p>',
                        vd:'XMzM4Nzc1MDk0OA',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp12.png'
                    },
                    {
                        tit:'长枪',
                        des:'<p>无间隙突击和顶级的抵御功能，以保护系的动作来确保战斗中自身的安全。</p>',
                        vd:'XMzM4Nzc1MTQ4NA',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp13.png'
                    },
                    {
                        tit:'重弩',
                        des:'<p>可发射强大威力子弹的远距离武器，“机关龙弹”、“狙击龙弹”等，可填装强大的特殊子弹。</p>',
                        vd:'XMzM4Nzc1MTUwOA',
                        pic:'http://image.gamersky.com/zqimg/mhw/pc/wp14.png'
                    }
                ]
            },
            npc:{
                name:'NPC',
                con:[
                    {
                        tit:'柜台小姐',
                        des:'<p>她是整理情报的专家“编辑者”。会和猎人一起行动，并且整理内容量庞大的调查内容。因为公会推荐，以及本人强烈希望，所以才会来到新大陆。个性活泼开朗，座右铭是“犹豫的话就先吃吃看吧！”</p><p>会和玩家一起行动，有如搭档的存在。</p><p>柜台小姐会和身为猎人的玩家一起行动，在据点里或是狩猎场的营地当中负责支援猎人。想要承接任务时就要先和她交谈。</p>',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/npc01b.jpg',
                        smlpic:'http://image.gamersky.com/zqimg/mhw/pc/npc01s.jpg'
                    },
                    {
                        tit:'总司令',
                        des:'<p>他是负责指挥调查团的人物，也是在四十年前踏上新大陆的第一期调查团成员之一，以冷静的指挥，有时又会提出大胆计策来引导调查团。深受调查团员信任。</p>',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/npc02b.jpg',
                        smlpic:'http://image.gamersky.com/zqimg/mhw/pc/npc02s.jpg'
                    },
                    {
                        tit:'调查班领队',
                        des:'<p>负责领导在狩猎场进行实地调查的调查班，领袖风范十足的青年猎人。是总司令的孙子，也是调查团中唯一生在新大陆长在新大陆的成员。作为活在新大陆的前辈，会传授给玩家各种知识。</p>',
                        bigpic:'http://image.gamersky.com/zqimg/mhw/pc/npc03b.jpg',
                        smlpic:'http://image.gamersky.com/zqimg/mhw/pc/npc03s.jpg'
                    }
                ]
            }
        }
    }
};
var pageState = {
    choiceWp:false
};
//预加载图片
 var preLoadPicsLists = {
     list1: [
         pageConfig.imglist.begin.bg,
         pageConfig.imglist.comm.bg

     ],
     list2:[
         pageConfig.imglist.end.bg
     ]
 };